import type { Locale } from "@/lib/i18n";

type Cluster = "geo" | "technical" | "content";
type Seed = {
  slug: string;
  cluster: Cluster;
  bg: { title: string; definition: string; problem: string; outcome: string };
  en: { title: string; definition: string; problem: string; outcome: string };
};

const seeds: Seed[] = [
  { slug: "geo-sreshtu-seo", cluster: "geo", bg: { title: "GEO срещу SEO: разлики, зависимости и обща основа", definition: "SEO подобрява откриването и разбирането в търсачки, а GEO разширява работата към генеративни системи, интерпретиране на същности и готовност за цитиране.", problem: "Разглеждането им като конкуриращи се дисциплини води до пропуски във възможността за обхождане, съдържанието и доказателствата.", outcome: "Една обща система, в която техническата SEO основа поддържа по-ясна AI видимост." }, en: { title: "GEO vs SEO: Differences, Dependencies, and a Shared Foundation", definition: "SEO improves discovery and understanding in search engines, while GEO extends the work toward generative systems, entity interpretation, and citation readiness.", problem: "Treating them as competing disciplines creates gaps in crawlability, content, and evidence.", outcome: "One connected system where technical SEO supports clearer AI visibility." } },
  { slug: "kak-chatgpt-izbira-iztochnitsi", cluster: "geo", bg: { title: "Как ChatGPT избира и използва източници", definition: "ChatGPT може да използва индексирани, директно достъпни и партньорски източници според режима, заявката и наличната retrieval система.", problem: "Няма един публичен списък от сигнали, който гарантира цитиране, а отговорите могат да комбинират различни източници.", outcome: "Съдържание, което е достъпно, конкретно, последователно и подкрепено от ясни entity сигнали." }, en: { title: "How ChatGPT Selects and Uses Sources", definition: "ChatGPT may use indexed, directly accessible, and partner sources depending on the mode, query, and available retrieval system.", problem: "There is no single public signal list that guarantees citation, and answers may combine multiple sources.", outcome: "Content that is accessible, specific, consistent, and supported by clear entity signals." } },
  { slug: "kak-gemini-izbira-iztochnitsi", cluster: "geo", bg: { title: "Как Gemini формира отговори и избира източници", definition: "Gemini комбинира контекст от Google системи, достъпно уеб съдържание и сигнали за релевантност според конкретната заявка.", problem: "Слабо разграничени брандове, непоследователни услуги и сходни имена могат да доведат до смесване на същности.", outcome: "Ясно разграничена организация с последователно име, локация, услуги, профили и доказателства." }, en: { title: "How Gemini Forms Answers and Selects Sources", definition: "Gemini combines context from Google systems, accessible web content, and relevance signals according to the query.", problem: "Poorly differentiated brands, inconsistent services, and similar names can cause entity confusion.", outcome: "A clearly differentiated organization with consistent name, location, services, profiles, and evidence." } },
  { slug: "kak-rabotyat-google-ai-overviews", cluster: "geo", bg: { title: "Как работят Google AI Overviews", definition: "AI Overviews създават синтезиран отговор за подходящи заявки и показват поддържащи връзки, когато системата прецени, че генерирано обобщение е полезно.", problem: "Оптимизацията само за кратка ключова дума не осигурява ясни пасажи, надежден контекст или възможност за обхождане.", outcome: "Полезни страници с ясна тема, семантична структура, точни твърдения и достъпни поддържащи раздели." }, en: { title: "How Google AI Overviews Work", definition: "AI Overviews create a synthesized answer for suitable queries and surface supporting links when the system determines that a generative summary is useful.", problem: "Optimizing only for a short keyword does not provide clear passages, reliable context, or crawl eligibility.", outcome: "Useful pages with a clear topic, semantic structure, precise claims, and accessible supporting sections." } },
  { slug: "entity-seo-obyasneno", cluster: "geo", bg: { title: "Entity SEO: как търсачките разграничават брандове и услуги", definition: "Entity SEO подрежда устойчивите факти и отношения около организация, услуга, място, профил и съдържание.", problem: "Когато името е сходно с други компании, общите фрази и непълните профили увеличават риска от погрешно класифициране.", outcome: "По-стабилно разбиране на това кой е брандът, какво предлага и с кои теми е свързан." }, en: { title: "Entity SEO: How Search Systems Distinguish Brands and Services", definition: "Entity SEO organizes stable facts and relationships around an organization, service, place, profile, and content.", problem: "When a name resembles other companies, generic language and incomplete profiles increase the risk of incorrect classification.", outcome: "More stable understanding of who the brand is, what it offers, and which topics it is connected to." } },
  { slug: "ai-visibility-obyasneno", cluster: "geo", bg: { title: "AI visibility: какво означава реално", definition: "AI visibility е способността на генеративни системи да открият, разберат и представят бранда коректно в релевантен контекст.", problem: "Единичен тест или споменаване не доказва устойчиво присъствие, защото моделите, механизмите за извличане и заявките се променят.", outcome: "Набор от последователни сигнали, полезно съдържание и външно потвърждение, наблюдавани във времето." }, en: { title: "AI Visibility: What It Actually Means", definition: "AI visibility is the ability of generative systems to discover, understand, and present a brand correctly in a relevant context.", problem: "A single test or mention does not demonstrate stable presence because models, retrieval, and queries change.", outcome: "A set of consistent signals, useful content, and external corroboration observed over time." } },
  { slug: "optimizatsiya-za-ai-tarsene", cluster: "geo", bg: { title: "Как да оптимизираме сайт за AI търсене", definition: "Оптимизацията за AI търсене започва със сайт, достъпен за обхождане, ясна информационна архитектура, конкретни отговори и последователни същности.", problem: "Добавянето на един файл или структурирани данни без качествено съдържание не създава авторитет или готовност за цитиране.", outcome: "Система от страници за услуги, статии, казуси, структурирани данни и реални външни сигнали." }, en: { title: "How to Optimize a Website for AI Search", definition: "AI search optimization starts with a crawlable website, clear information architecture, specific answers, and consistent entities.", problem: "Adding one file or schema block without useful content does not create authority or citation readiness.", outcome: "A system of service pages, articles, case studies, structured data, and genuine external signals." } },
  { slug: "kakvo-pravi-branda-tsitiruem", cluster: "geo", bg: { title: "Какво прави един бранд цитируем от AI системи", definition: "Цитируемият бранд публикува ясни, конкретни и проверими твърдения в контекст, който може да бъде извлечен без загуба на смисъл.", problem: "Общи рекламни фрази, недоказани суперлативи и липса на първични доказателства намаляват стойността като източник.", outcome: "Оригинални методологии, потвърдени резултати, ясни авторски позиции и стабилни URL адреси." }, en: { title: "What Makes a Brand Citable by AI Systems", definition: "A citable brand publishes clear, specific, verifiable claims in context that can be extracted without losing meaning.", problem: "Generic marketing language, unsupported superlatives, and missing primary evidence reduce source value.", outcome: "Original methodologies, verified outcomes, clear editorial positions, and stable URLs." } },
  { slug: "structured-data-i-ai", cluster: "geo", bg: { title: "Как структурирани данни помагат на AI и търсачките", definition: "Структурираните данни описват типа на видимото съдържание и отношенията между организация, услуга, статия, breadcrumb и творческа работа.", problem: "Структурираните данни не поправят слабо съдържание и стават рискови, когато съдържат невидими или неверни твърдения.", outcome: "Валидно маркиране, което съвпада с реалното съдържание и използва устойчиви @id отношения." }, en: { title: "How Structured Data Helps AI and Search Systems", definition: "Structured data describes visible content types and relationships between an organization, service, article, breadcrumb, and creative work.", problem: "Schema does not repair weak content and becomes risky when it contains invisible or false claims.", outcome: "Valid markup coverage aligned with visible content and stable @id relationships." } },
  { slug: "kak-rabotyat-llm-crawlers", cluster: "geo", bg: { title: "Как работят LLM crawlers и какво могат да достъпят", definition: "Различните AI доставчици използват отделни user agents, crawling политики и retrieval механизми с различни цели.", problem: "Блокирането или разрешаването на един crawler не определя поведението на всички AI продукти.", outcome: "Ясна robots политика, публично достъпно съдържание и информирано решение за отделните crawlers." }, en: { title: "How LLM Crawlers Work and What They Can Access", definition: "AI providers use separate user agents, crawling policies, and retrieval mechanisms for different purposes.", problem: "Blocking or allowing one crawler does not determine the behaviour of every AI product.", outcome: "A clear robots policy, publicly accessible content, and informed decisions for individual crawlers." } },
  { slug: "podobryavane-na-ai-otkrivaemost", cluster: "geo", bg: { title: "Как да подобрим AI откриваемостта на бизнес сайт", definition: "AI откриваемостта зависи от достъпност, тематично покритие, последователност на същностите, вътрешни връзки и външни източници.", problem: "Страница с много ключови думи, но без ясна функция и доказателства, остава трудна за надеждно интерпретиране.", outcome: "Покритие на реалните въпроси, ясни връзки между услугите и независими сигнали за доверие." }, en: { title: "How to Improve AI Discoverability for a Business Website", definition: "AI discoverability depends on accessibility, topical coverage, entity consistency, internal links, and external sources.", problem: "A keyword-heavy page without a clear purpose or evidence remains difficult to interpret reliably.", outcome: "Coverage of real questions, clear service relationships, and independent trust signals." } },
  { slug: "izgrazhdane-na-entity-authority", cluster: "geo", bg: { title: "Как се изгражда entity authority", definition: "Entity authority се натрупва, когато един и същ бранд е описван последователно чрез собствени страници, профили, публикации и независими източници.", problem: "Честата смяна на термини, непълните профили и противоречивите описания размиват идентичността.", outcome: "Устойчиво ядро от факти, теми, доказателства и връзки, което се потвърждава от повече от един източник." }, en: { title: "How to Build Entity Authority", definition: "Entity authority accumulates when the same brand is described consistently across owned pages, profiles, publications, and independent sources.", problem: "Frequent terminology changes, incomplete profiles, and contradictory descriptions weaken identity.", outcome: "A stable core of facts, topics, evidence, and relationships corroborated by more than one source." } },
  { slug: "badeshteto-na-tarseneto-v-ai-erata", cluster: "geo", bg: { title: "Бъдещето на търсенето в AI ерата", definition: "Търсенето се развива от списък с връзки към комбинация от резултати, синтезирани отговори, multimodal context и директни действия.", problem: "Тактиките, изградени само около ranking на една страница за една фраза, стават по-нестабилни.", outcome: "Инвестиция в ясна entity система, оригинално съдържание, техническа достъпност и собствена аудитория." }, en: { title: "The Future of Search in the AI Era", definition: "Search is evolving from a list of links into a combination of results, synthesized answers, multimodal context, and direct actions.", problem: "Tactics built only around ranking one page for one phrase become less resilient.", outcome: "Investment in a clear entity system, original content, technical accessibility, and an owned audience." } },
  { slug: "zashto-izpolzvame-astro", cluster: "technical", bg: { title: "Защо използваме Astro, когато проектът го изисква", definition: "Astro е content-focused web framework, който позволява архитектура с приоритет върху статичното генериране и минимално количество JavaScript в браузъра по подразбиране.", problem: "Технологията не е универсален отговор и грешният избор може да усложни редакцията или динамичните функции.", outcome: "Astro се използва там, където производителността, архитектурата на съдържанието и ниският риск, свързан със средата за изпълнение, са реално предимство." }, en: { title: "Why We Use Astro When the Project Calls for It", definition: "Astro is a content-focused web framework that supports static-first delivery and minimal client JavaScript by default.", problem: "The technology is not a universal answer, and the wrong choice can complicate editing or dynamic functionality.", outcome: "Astro is used where performance, content architecture, and low runtime risk create a real advantage." } },
  { slug: "astro-sreshtu-wordpress", cluster: "technical", bg: { title: "Astro срещу WordPress: избор според проекта", definition: "Astro и WordPress решават различни проблеми: единият дава архитектура с приоритет върху статичното генериране, а другият — зряла CMS и екосистема от разширения.", problem: "Изборът по популярност или личен навик пренебрегва редакционния процес, собствеността и риска при поддръжката.", outcome: "Решение според съдържанието, екипа, integrations, сигурността и дългосрочната поддръжка." }, en: { title: "Astro vs WordPress: Choosing for the Project", definition: "Astro and WordPress solve different problems: one provides static-first architecture, while the other offers a mature CMS and plugin ecosystem.", problem: "Choosing by popularity or personal habit ignores editorial workflow, ownership, and maintenance risk.", outcome: "A decision based on content, team, integrations, security, and long-term maintenance." } },
  { slug: "core-web-vitals-obyasneni", cluster: "technical", bg: { title: "Core Web Vitals: LCP, INP и CLS обяснени", definition: "Core Web Vitals измерват зареждането, отзивчивостта при взаимодействие и визуалната стабилност чрез LCP, INP и CLS.", problem: "Един добър лабораторен тест не доказва стабилно преживяване за всички реални потребители.", outcome: "Комбинация от данни от реални потребители, лабораторна диагностика и контрол върху ресурсите, средата за изпълнение и оформлението." }, en: { title: "Core Web Vitals: LCP, INP, and CLS Explained", definition: "Core Web Vitals measure loading, interaction responsiveness, and visual stability through LCP, INP, and CLS.", problem: "One strong laboratory test does not prove a stable experience for every real user.", outcome: "A combination of field data, laboratory diagnosis, and control over assets, runtime, and layout." } },
  { slug: "performance-first-websites", cluster: "technical", bg: { title: "Сайтове с приоритет върху производителността без визуален компромис", definition: "Подходът с приоритет върху производителността означава скоростта и стабилността да бъдат архитектурни изисквания от началото, а не финално орязване.", problem: "Късната оптимизация често премахва съдържание или ефекти, без да поправи тежката среда за изпълнение и модела на доставяне.", outcome: "Дизайнът, ресурсите, шрифтовете, компонентите и хостингът се планират като една производителна система." }, en: { title: "Performance-First Websites Without Visual Compromise", definition: "Performance-first means treating speed and stability as architectural requirements from the beginning rather than a final reduction exercise.", problem: "Late optimization often removes content or effects without fixing a heavy runtime and delivery model.", outcome: "Design, assets, fonts, components, and hosting are planned as one performant system." } },
  { slug: "osnovi-na-tehnicheskoto-seo", cluster: "technical", bg: { title: "Основи на техническото SEO", definition: "Техническото SEO поддържа откриването, визуализирането, индексирането и правилното консолидиране на URL адреси.", problem: "Малки несъответствия в redirects, canonical, sitemap и вътрешните връзки могат да натрупат ненужен crawl шум.", outcome: "Една canonical URL система, чисти кодове на отговор, валидна schema и проследимо покритие в индекса." }, en: { title: "Technical SEO Fundamentals", definition: "Technical SEO supports discovery, rendering, indexing, and correct URL consolidation.", problem: "Small inconsistencies in redirects, canonical, sitemaps, and internal links can accumulate unnecessary crawl noise.", outcome: "One canonical URL system, clean statuses, valid schema, and traceable index coverage." } },
  { slug: "web-dostapnost", cluster: "technical", bg: { title: "Уеб достъпност като част от качеството", definition: "Достъпността позволява съдържанието и функциите да бъдат използвани с различни устройства, способности и assistive technologies.", problem: "Добавянето на aria labels без semantic структура не решава keyboard, contrast и focus проблемите.", outcome: "Правилен HTML, heading order, labels, focus states, contrast и тестване с keyboard." }, en: { title: "Website Accessibility as a Quality Standard", definition: "Accessibility allows content and functionality to be used across different devices, abilities, and assistive technologies.", problem: "Adding aria labels without semantic structure does not solve keyboard, contrast, or focus problems.", outcome: "Correct HTML, heading order, labels, focus states, contrast, and keyboard testing." } },
  { slug: "moderna-web-arhitektura", cluster: "technical", bg: { title: "Модерна уеб архитектура без ненужна сложност", definition: "Модерната архитектура избира rendering, content, data и deployment модели според реалните нужди.", problem: "Добавянето на framework, API и client state без функция увеличава риска, разхода и поддръжката.", outcome: "Най-малката достатъчна система с ясна собственост, monitoring и път за развитие." }, en: { title: "Modern Website Architecture Without Unnecessary Complexity", definition: "Modern architecture selects rendering, content, data, and deployment models according to actual needs.", problem: "Adding frameworks, APIs, and client state without a function increases risk, cost, and maintenance.", outcome: "The smallest sufficient system with clear ownership, monitoring, and a path for growth." } },
  { slug: "dobri-praktiki-za-structured-data", cluster: "technical", bg: { title: "Структурирани данни: добри практики и реални ограничения", definition: "Структурираните данни правят видимото съдържание по-разбираемо за машините чрез речника на Schema.org.", problem: "Прекомерното покритие със структурирани данни, неверните типове и невидимите твърдения създават шум и риск за съответствието.", outcome: "Минимално достатъчни структурирани данни, проверени и синхронизирани с текста на страницата." }, en: { title: "Structured Data Best Practices and Real Limitations", definition: "Structured data makes visible content more machine-readable through schema.org vocabulary.", problem: "Excessive markup, incorrect types, and invisible claims create noise and compliance risk.", outcome: "The minimum sufficient schema, validated and synchronized with the page content." } },
  { slug: "content-strategy-ne-e-kalendar", cluster: "content", bg: { title: "Content strategy не е календар за публикации", definition: "Content strategy определя аудитория, цели, теми, формати, ownership и критерии за стойност.", problem: "Календарът без ясна роля произвежда обем, но не изгражда разпознаваемост или доверие.", outcome: "Редакционна система, в която всяко съдържание има функция и връзка с реална бизнес цел." }, en: { title: "Content Strategy Is Not a Publishing Calendar", definition: "Content strategy defines audience, goals, topics, formats, ownership, and criteria for value.", problem: "A calendar without a clear role produces volume without building recognition or trust.", outcome: "An editorial system where every piece has a function and a relationship to a real business goal." } },
  { slug: "content-creation-kato-sistema", cluster: "content", bg: { title: "Създаване на съдържание като система", definition: "Съдържанието работи като система, когато текст, визуален формат, канал и следваща стъпка използват обща логика.", problem: "Изолираните публикации изискват постоянна импровизация и рядко натрупват тематичен авторитет.", outcome: "Повтаряеми формати, ясни теми и content assets, които могат да се използват в повече от един канал." }, en: { title: "Content Creation as a System", definition: "Content works as a system when copy, visual format, channel, and next step follow shared logic.", problem: "Isolated posts require constant improvisation and rarely accumulate topical authority.", outcome: "Repeatable formats, clear themes, and content assets that can work across more than one channel." } },
  { slug: "social-media-management-s-rol", cluster: "content", bg: { title: "Управление на социални медии с ясна роля", definition: "Управлението на социални медии свързва стратегия, производство, публикуване, community context и измерване.", problem: "Когато услугата се свежда до брой публикации, каналът губи връзка с позиционирането и реалните цели.", outcome: "Управляем ритъм, последователни формати и ясна причина за всяка комуникационна линия." }, en: { title: "Social Media Management with a Clear Role", definition: "Social media management connects strategy, production, publishing, community context, and measurement.", problem: "When the service is reduced to post count, the channel loses its relationship with positioning and real goals.", outcome: "A manageable rhythm, consistent formats, and a clear reason for every communication line." } },
  { slug: "brand-communication", cluster: "content", bg: { title: "Бранд комуникация отвъд визуалната идентичност", definition: "Бранд комуникацията превежда позиционирането в език, теми, доказателства, реакции и поведение по канали.", problem: "Силното лого не може да компенсира противоречив tone of voice или неясни обещания.", outcome: "Разпознаваем начин на говорене, който остава последователен в сайт, социални медии и реклама." }, en: { title: "Brand Communication Beyond Visual Identity", definition: "Brand communication translates positioning into language, topics, evidence, responses, and channel behaviour.", problem: "A strong logo cannot compensate for a contradictory tone of voice or unclear promises.", outcome: "A recognizable way of speaking that remains consistent across website, social media, and advertising." } },
  { slug: "advertising-strategy-bez-shum", cluster: "content", bg: { title: "Рекламна стратегия без излишен шум", definition: "Рекламната стратегия свързва аудитория, оферта, послание, формат, канал и измерим резултат.", problem: "Повече визии и по-силен език не поправят слаба оферта или липса на конкретна следваща стъпка.", outcome: "Кампанийна система с ясна хипотеза, подходящ creative и критерий за решение." }, en: { title: "Advertising Strategy Without Unnecessary Noise", definition: "Advertising strategy connects audience, offer, message, format, channel, and measurable outcome.", problem: "More visuals and louder language do not repair a weak offer or a missing next step.", outcome: "A campaign system with a clear hypothesis, appropriate creative, and a decision criterion." } },
  { slug: "digital-campaign-planning", cluster: "content", bg: { title: "Как се планира дигитална кампания", definition: "Дигиталната кампания е ограничена във времето система от послания, assets, landing context, distribution и measurement.", problem: "Кампания без обща структура се разпада на несвързани публикации и реклами.", outcome: "Единна линия от първия контакт до landing страницата и следващото действие." }, en: { title: "How to Plan a Digital Campaign", definition: "A digital campaign is a time-bound system of messages, assets, landing context, distribution, and measurement.", problem: "A campaign without a shared structure breaks into disconnected posts and advertisements.", outcome: "One coherent line from the first contact to the landing page and next action." } },
  { slug: "creative-direction", cluster: "content", bg: { title: "Creative direction: как се запазва обща посока", definition: "Creative direction определя принципите, по които различни текстове, визии и формати принадлежат към една комуникация.", problem: "Без ясни критерии всяко ново изпълнение започва от нулата и визуалният език постепенно се размива.", outcome: "Рамка за решения, която позволява разнообразие без загуба на разпознаваемост." }, en: { title: "Creative Direction: Maintaining a Shared Direction", definition: "Creative direction defines the principles that make different copy, visuals, and formats belong to one communication system.", problem: "Without clear criteria, every execution starts from zero and the visual language gradually drifts.", outcome: "A decision framework that allows variety without losing recognition." } },
  { slug: "editorial-system-for-brands", cluster: "content", bg: { title: "Редакционна система за бранд съдържание", definition: "Редакционната система описва темите, типовете публикации, стандартите и връзките между текущо и evergreen съдържание.", problem: "Случайният избор на теми създава неравна стойност и не изгражда ясна експертна територия.", outcome: "Баланс между практически отговори, гледна точка, доказателства и service relevance." }, en: { title: "An Editorial System for Brand Content", definition: "An editorial system defines topics, publication types, standards, and relationships between timely and evergreen content.", problem: "Random topic selection creates uneven value and does not build a clear area of expertise.", outcome: "A balance of practical answers, perspective, evidence, and service relevance." } },
  { slug: "content-repurposing", cluster: "content", bg: { title: "Content repurposing без механично копиране", definition: "Repurposing превежда една силна идея в подходящи формати за различни канали, без да копира дословно.", problem: "Еднакъв текст във всяка платформа пренебрегва контекста, поведението и очакванията на аудиторията.", outcome: "Едно content ядро с различни входове, дължини и действия според канала." }, en: { title: "Content Repurposing Without Mechanical Duplication", definition: "Repurposing translates one strong idea into appropriate formats for different channels without copying it verbatim.", problem: "The same text on every platform ignores context, behaviour, and audience expectations.", outcome: "One content core with different entry points, lengths, and actions for each channel." } },
  { slug: "social-media-content-pillars", cluster: "content", bg: { title: "Content pillars за социални медии", definition: "Content pillars са устойчиви тематични линии, които помагат на канала да покрива експертиза, доказателства, контекст и действие.", problem: "Твърде общите pillars не дават критерий за избор, а твърде тесните бързо се изчерпват.", outcome: "Няколко ясни линии с различна функция и достатъчно пространство за развитие." }, en: { title: "Content Pillars for Social Media", definition: "Content pillars are stable thematic lines that help a channel cover expertise, evidence, context, and action.", problem: "Pillars that are too broad provide no selection criteria, while pillars that are too narrow are quickly exhausted.", outcome: "A small number of clear lines with different functions and room for development." } },
  { slug: "tone-of-voice-in-practice", cluster: "content", bg: { title: "Tone of voice в практическа употреба", definition: "Tone of voice превръща бранд позицията в повторяеми езикови решения за различни ситуации.", problem: "Списък от прилагателни не помага, ако няма примери за заглавия, CTA, отговори и трудни комуникационни моменти.", outcome: "Работни правила, примери и граници, които запазват един глас без изкуствена еднаквост." }, en: { title: "Tone of Voice in Practical Use", definition: "Tone of voice translates brand position into repeatable language decisions for different situations.", problem: "A list of adjectives is not useful without examples for headings, CTAs, responses, and difficult communication moments.", outcome: "Working rules, examples, and boundaries that maintain one voice without artificial uniformity." } },
  { slug: "content-quality-control", cluster: "content", bg: { title: "Контрол на качеството при съдържание", definition: "Content QA проверява точност, структура, tone, links, accessibility, metadata и готовност за публикуване.", problem: "Правописната проверка сама не открива двусмислие, повторения, недоказани твърдения или слаб next step.", outcome: "Редакционен checklist, който защитава смисъла и техническата цялост преди publish." }, en: { title: "Quality Control for Content", definition: "Content QA checks accuracy, structure, tone, links, accessibility, metadata, and publication readiness.", problem: "Spell checking alone does not reveal ambiguity, repetition, unsupported claims, or a weak next step.", outcome: "An editorial checklist that protects meaning and technical integrity before publication." } },
  { slug: "measuring-content-value", cluster: "content", bg: { title: "Как се измерва стойността на съдържанието", definition: "Стойността на съдържанието се измерва според функцията му: откриване, разбиране, доверие, действие или поддръжка.", problem: "Еднакви metrics за всяка публикация водят до погрешни решения и производство заради самия обем.", outcome: "Набор от показатели, свързани с intent и ролята на конкретния формат." }, en: { title: "How to Measure Content Value", definition: "Content value is measured according to its function: discovery, understanding, trust, action, or support.", problem: "Using the same metrics for every publication leads to poor decisions and production for volume alone.", outcome: "A set of indicators connected to intent and the role of the specific format." } },
  { slug: "community-management-context", cluster: "content", bg: { title: "Community management като част от бранд комуникацията", definition: "Community management включва начина, по който брандът отговаря, модерира, насочва и запазва tone в публични разговори.", problem: "Бързият отговор без контекст може да създаде повече риск от забавения, но точен и последователен отговор.", outcome: "Ясни response правила, escalation логика и човешки тон, съобразен с бранда." }, en: { title: "Community Management as Brand Communication", definition: "Community management includes how a brand responds, moderates, directs, and maintains tone in public conversations.", problem: "A fast response without context can create more risk than a slower, accurate, consistent one.", outcome: "Clear response rules, escalation logic, and a human tone aligned with the brand." } },
  { slug: "campaign-landing-content", cluster: "content", bg: { title: "Съдържание за campaign landing page", definition: "Campaign landing content свързва обещанието от рекламата с контекст, доказателство и едно ясно действие.", problem: "Когато рекламата и landing страницата използват различен език, потребителят трябва сам да възстанови връзката.", outcome: "Последователен message match и достатъчно информация за уверено решение." }, en: { title: "Content for a Campaign Landing Page", definition: "Campaign landing content connects the advertising promise with context, evidence, and one clear action.", problem: "When the advertisement and landing page use different language, the user must reconstruct the relationship alone.", outcome: "Consistent message match and enough information for a confident decision." } },
  { slug: "content-for-service-pages", cluster: "content", bg: { title: "Как се пише съдържание за service pages", definition: "Добрата service page обяснява какво е услугата, за кого е, какво включва, как работи и каква е следващата стъпка.", problem: "Общите обещания и дългите списъци без контекст не помагат на потребителя да оцени fit и обхват.", outcome: "Страница, която квалифицира, отговаря на реални въпроси и подкрепя SEO и AI retrieval." }, en: { title: "How to Write Content for Service Pages", definition: "A strong service page explains what the service is, who it is for, what it includes, how it works, and the next step.", problem: "Generic promises and long context-free lists do not help users evaluate fit or scope.", outcome: "A page that qualifies, answers real questions, and supports SEO and AI retrieval." } },
  { slug: "proof-in-brand-content", cluster: "content", bg: { title: "Доказателства в бранд съдържанието", definition: "Доказателството може да бъде потвърден резултат, процес, реален artifact, testimonial или ясно ограничено твърдение.", problem: "Недоказаните числа и общите superlatives намаляват доверието и могат да бъдат повторени неточно от AI системи.", outcome: "Разграничение между факт, опит, мнение и цел, подкрепено с подходящ контекст." }, en: { title: "Evidence in Brand Content", definition: "Evidence may be a verified result, process, real artifact, testimonial, or clearly limited claim.", problem: "Unsupported numbers and generic superlatives reduce trust and may be repeated inaccurately by AI systems.", outcome: "A distinction between fact, experience, opinion, and objective supported by appropriate context." } },
  { slug: "content-governance", cluster: "content", bg: { title: "Content governance за растящ сайт", definition: "Content governance определя кой създава, проверява, одобрява, обновява и архивира съдържанието.", problem: "Без ownership старите факти, дублираните страници и невалидните линкове се натрупват незабелязано.", outcome: "Ясен lifecycle за публикации, metadata, translations, legal review и периодична актуализация." }, en: { title: "Content Governance for a Growing Website", definition: "Content governance defines who creates, checks, approves, updates, and archives content.", problem: "Without ownership, outdated facts, duplicate pages, and invalid links accumulate unnoticed.", outcome: "A clear lifecycle for publications, metadata, translations, legal review, and periodic updates." } },
  { slug: "content-and-geo", cluster: "content", bg: { title: "Как съдържанието подкрепя GEO", definition: "Съдържанието подкрепя GEO, когато покрива конкретни въпроси, използва ясни същности и предоставя достатъчно контекст за надеждно извличане.", problem: "Текст, написан само с висока плътност на ключовите думи, не изгражда полезна структура на знанията.", outcome: "Редакционни клъстери, в които услугите, определенията, методологиите и доказателствата се свързват естествено." }, en: { title: "How Content Supports GEO", definition: "Content supports GEO when it covers specific questions, uses clear entities, and provides enough context for reliable retrieval.", problem: "Text written only for keyword density does not build a useful knowledge structure.", outcome: "Editorial clusters where services, definitions, methodologies, and evidence connect naturally." } },
];

const clusterConfig = {
  geo: { category: "seo-geo", service: "/services/geo" },
  technical: { category: "web-presence", service: "/services/technical-seo" },
  content: { category: "content", service: "/services/content-creation" },
} as const;

function createSections(locale: Locale, seed: Seed) {
  const copy = seed[locale];
  const bg = locale === "bg";
  return [
    { title: bg ? "Определение" : "Definition", paragraphs: [copy.definition, bg ? "Терминът има стойност само когато е свързан с конкретен процес, видимо съдържание и проверими ограничения. Затова го разглеждаме като част от общата система за бранд, сайт и дигитално присъствие, а не като изолиран етикет." : "The term is useful only when connected to a specific process, visible content, and verifiable limitations. We therefore treat it as part of the wider brand, website, and digital presence system rather than an isolated label."] },
    { title: bg ? "Основният проблем" : "The central problem", paragraphs: [copy.problem, bg ? "Проблемът обикновено не е липса на още един инструмент. Той е липса на ясна архитектура, ownership и критерий кое твърдение е факт, кое е интерпретация и кое все още трябва да бъде потвърдено." : "The problem is usually not the absence of another tool. It is the absence of clear architecture, ownership, and criteria separating fact, interpretation, and claims that still require confirmation."] },
    { title: bg ? "Как работи системата" : "How the system works", paragraphs: [bg ? "Започваме от намерението и основната същност. След това подреждаме страниците, темите, вътрешните връзки, метаданните и доказателствата. Техническите сигнали подкрепят съдържанието, но не го заменят. Всяка страница трябва да има уникална функция и да води към логична следваща стъпка." : "We begin with intent and the primary entity. We then organize pages, topics, internal links, metadata, and evidence. Technical signals support content but do not replace it. Every page needs a unique function and a logical next step.", copy.outcome] },
    { title: bg ? "Методология на d . media" : "The d . media methodology", paragraphs: [bg ? "Работим в последователност: audit, карта на отношенията, приоритет, implementation и повторна validation. Системните проблеми се поправят в template, routing или data layer, вместо да се добавят отделни patch-ове за всеки URL. Това намалява риска от visual, SEO и content drift." : "We work in sequence: audit, relationship map, priority, implementation, and repeated validation. Systemic problems are corrected in templates, routing, or the data layer instead of adding separate patches for every URL. This reduces visual, SEO, and content drift.", bg ? "Когато темата включва външна платформа или алгоритъм, разграничаваме официално документираните факти от нашите наблюдения. Не представяме llms.txt, schema, PageSpeed или единичен AI тест като гаранция за ranking, citation или business result." : "When a topic involves an external platform or algorithm, we separate officially documented facts from our observations. We do not present llms.txt, schema, PageSpeed, or one AI test as a guarantee of ranking, citation, or business results."] },
    { title: bg ? "Практическа проверка" : "Practical validation", paragraphs: [bg ? "Проверката включва реалните URL адреси, кодовете на отговор, canonical и езиковите връзки, семантичните заглавия, вътрешните връзки и видимото съдържание. При проблеми с производителността и браузъра използваме подходящия engine и устройство. При AI видимост сравняваме повече от една формулировка и повече от един момент във времето." : "Validation covers real URLs, response statuses, canonical and language relationships, semantic headings, internal links, and visible content. Performance and browser problems are tested in the relevant engine and device. AI visibility is compared across more than one prompt formulation and more than one point in time."] },
    { title: bg ? "Какво означава за бизнеса" : "What this means for a business", paragraphs: [copy.outcome, bg ? "Практическата стойност е по-малко неяснота: потребителят разбира услугата, търсачката разпознава функцията на страницата, а AI системата разполага с по-конкретен контекст. Това не премахва конкуренцията, но създава по-добра основа за разпознаваемост и доверие." : "The practical value is reduced ambiguity: users understand the service, search engines recognize the page purpose, and AI systems receive more specific context. This does not remove competition, but it creates a stronger foundation for recognition and trust."] },
    { title: bg ? "Ограничения" : "Limitations", paragraphs: [bg ? "Нито една техническа или съдържателна промяна не може да гарантира конкретна позиция, rich result или AI цитиране. Резултатът зависи от качеството на източника, конкуренцията, заявката, външното потвърждение и системите на съответната платформа." : "No technical or content change can guarantee a specific ranking, rich result, or AI citation. Outcomes depend on source quality, competition, the query, external corroboration, and the systems operated by each platform."] },
    { title: bg ? "Следваща стъпка" : "Next step", paragraphs: [bg ? "Следващата стъпка е да се определи текущото състояние и най-голямата празнина: технически достъп, content coverage, entity consistency, доказателства или поддръжка. Така работата започва от реален проблем, а не от списък с модни оптимизации." : "The next step is to determine the current state and the largest gap: technical access, content coverage, entity consistency, evidence, or maintenance. This keeps the work grounded in a real problem rather than a list of fashionable optimizations."] },
  ];
}

export function getAuthorityArticles(locale: Locale) {
  const bg = locale === "bg";
  return seeds.map((seed, index) => {
    const copy = seed[locale];
    const config = clusterConfig[seed.cluster];
    const related = seeds.filter((item) => item.cluster === seed.cluster && item.slug !== seed.slug).slice(index % 3, index % 3 + 3).map((item) => item.slug);
    return {
      slug: seed.slug,
      category: config.category,
      datePublished: "2026-06-13",
      dateModified: "2026-06-13",
      readingTime: 8,
      title: copy.title,
      excerpt: copy.outcome,
      intro: copy.definition,
      metaTitle: copy.title,
      metaDescription: `${copy.definition} ${copy.outcome}`,
      seoTitle: copy.title,
      seoDescription: `${copy.definition} ${copy.outcome}`,
      author: "d . media",
      tags: [seed.cluster, "d . media", copy.title],
      keywords: [copy.title, seed.cluster, "d . media"],
      language: bg ? "bg-BG" : "en-US",
      featured: index < 3,
      draft: false,
      relatedPosts: related,
      sections: createSections(locale, seed),
      faqs: bg
        ? [
            { question: `Какво е най-важното при ${copy.title.toLowerCase()}?`, answer: `${copy.definition} Най-важна е връзката между ясното съдържание, техническата достъпност и проверимите доказателства.` },
            { question: "Може ли една промяна да гарантира резултат?", answer: "Не. Резултатът зависи от качеството на цялата система, конкуренцията, външните сигнали и решенията на съответната платформа." },
            { question: "Как започва практическата работа?", answer: "С audit на текущото състояние, карта на липсващите отношения и приоритет върху проблемите с реален ефект." },
          ]
        : [
            { question: `What matters most in ${copy.title.toLowerCase()}?`, answer: `${copy.definition} The most important factor is the relationship between clear content, technical accessibility, and verifiable evidence.` },
            { question: "Can one change guarantee an outcome?", answer: "No. Outcomes depend on the quality of the full system, competition, external signals, and decisions made by the relevant platform." },
            { question: "How does practical work begin?", answer: "With an audit of the current state, a map of missing relationships, and priority given to problems with a real effect." },
          ],
      relatedLinks: [
        { href: config.service, label: bg ? "Виж релевантната услуга" : "View the relevant service" },
        { href: "/case-studies", label: bg ? "Разгледай казусите" : "Explore case studies" },
      ],
      ctaTitle: bg ? "Ако темата е част от текущия ти проект, започни с контекст." : "If this topic is part of your current project, start with context.",
      ctaText: bg ? "Изпрати текущото състояние, целта и наличните сигнали. Ще върнем ясна следваща стъпка според реалния обхват." : "Send the current state, objective, and available signals. We will return a clear next step based on the actual scope.",
      ctaPrimaryLabel: bg ? "Изпрати проектен контекст" : "Send project context",
      ctaPrimaryHref: "/contact",
      ctaSecondaryLabel: bg ? "Разгледай услугата" : "Explore the service",
      ctaSecondaryHref: config.service,
    };
  });
}
