// Generated by scripts/process-motion-archive.mjs. Do not edit manually.
export const dMediaMotionArchive = [
  {
    "title": "d . media cinematic intro v1",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/001-cinematic-intro-d-media-cinematic-intro-v1-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/001-cinematic-intro-d-media-cinematic-intro-v1-mov.png",
    "bytes": 4486096
  },
  {
    "title": "d . media cinematic intro v10",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/002-cinematic-intro-d-media-cinematic-intro-v10-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/002-cinematic-intro-d-media-cinematic-intro-v10-mov.png",
    "bytes": 3020558
  },
  {
    "title": "d . media cinematic intro v11",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/003-cinematic-intro-d-media-cinematic-intro-v11-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/003-cinematic-intro-d-media-cinematic-intro-v11-mov.png",
    "bytes": 9357308
  },
  {
    "title": "d . media cinematic intro v12",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/004-cinematic-intro-d-media-cinematic-intro-v12-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/004-cinematic-intro-d-media-cinematic-intro-v12-mov.png",
    "bytes": 3915031
  },
  {
    "title": "d . media cinematic intro v13",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/005-cinematic-intro-d-media-cinematic-intro-v13-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/005-cinematic-intro-d-media-cinematic-intro-v13-mov.png",
    "bytes": 3749456
  },
  {
    "title": "d . media cinematic intro v14",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/006-cinematic-intro-d-media-cinematic-intro-v14-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/006-cinematic-intro-d-media-cinematic-intro-v14-mov.png",
    "bytes": 2809203
  },
  {
    "title": "d . media cinematic intro v15",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/007-cinematic-intro-d-media-cinematic-intro-v15-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/007-cinematic-intro-d-media-cinematic-intro-v15-mov.png",
    "bytes": 8356559
  },
  {
    "title": "d . media cinematic intro v16",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/008-cinematic-intro-d-media-cinematic-intro-v16-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/008-cinematic-intro-d-media-cinematic-intro-v16-mov.png",
    "bytes": 2614223
  },
  {
    "title": "d . media cinematic intro v17",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/009-cinematic-intro-d-media-cinematic-intro-v17-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/009-cinematic-intro-d-media-cinematic-intro-v17-mov.png",
    "bytes": 5287671
  },
  {
    "title": "d . media cinematic intro v18",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/010-cinematic-intro-d-media-cinematic-intro-v18-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/010-cinematic-intro-d-media-cinematic-intro-v18-mov.png",
    "bytes": 4864995
  },
  {
    "title": "d . media cinematic intro v19",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/011-cinematic-intro-d-media-cinematic-intro-v19-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/011-cinematic-intro-d-media-cinematic-intro-v19-mov.png",
    "bytes": 7521281
  },
  {
    "title": "d . media cinematic intro v2",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/012-cinematic-intro-d-media-cinematic-intro-v2-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/012-cinematic-intro-d-media-cinematic-intro-v2-mov.png",
    "bytes": 5220301
  },
  {
    "title": "d . media cinematic intro v20",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/013-cinematic-intro-d-media-cinematic-intro-v20-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/013-cinematic-intro-d-media-cinematic-intro-v20-mov.png",
    "bytes": 3135291
  },
  {
    "title": "d . media cinematic intro v21",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/014-cinematic-intro-d-media-cinematic-intro-v21-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/014-cinematic-intro-d-media-cinematic-intro-v21-mov.png",
    "bytes": 8226701
  },
  {
    "title": "d . media cinematic intro v22",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/015-cinematic-intro-d-media-cinematic-intro-v22-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/015-cinematic-intro-d-media-cinematic-intro-v22-mov.png",
    "bytes": 9366677
  },
  {
    "title": "d . media cinematic intro v23",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/016-cinematic-intro-d-media-cinematic-intro-v23-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/016-cinematic-intro-d-media-cinematic-intro-v23-mov.png",
    "bytes": 8827050
  },
  {
    "title": "d . media cinematic intro v24",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/017-cinematic-intro-d-media-cinematic-intro-v24-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/017-cinematic-intro-d-media-cinematic-intro-v24-mov.png",
    "bytes": 9000187
  },
  {
    "title": "d . media cinematic intro v25",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/018-cinematic-intro-d-media-cinematic-intro-v25-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/018-cinematic-intro-d-media-cinematic-intro-v25-mov.png",
    "bytes": 8458891
  },
  {
    "title": "d . media cinematic intro v26",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/019-cinematic-intro-d-media-cinematic-intro-v26-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/019-cinematic-intro-d-media-cinematic-intro-v26-mov.png",
    "bytes": 8015205
  },
  {
    "title": "d . media cinematic intro v27",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/020-cinematic-intro-d-media-cinematic-intro-v27-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/020-cinematic-intro-d-media-cinematic-intro-v27-mov.png",
    "bytes": 8156525
  },
  {
    "title": "d . media cinematic intro v28",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/021-cinematic-intro-d-media-cinematic-intro-v28-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/021-cinematic-intro-d-media-cinematic-intro-v28-mov.png",
    "bytes": 3857313
  },
  {
    "title": "d . media cinematic intro v29",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/022-cinematic-intro-d-media-cinematic-intro-v29-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/022-cinematic-intro-d-media-cinematic-intro-v29-mov.png",
    "bytes": 1215903
  },
  {
    "title": "d . media cinematic intro v3",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/023-cinematic-intro-d-media-cinematic-intro-v3-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/023-cinematic-intro-d-media-cinematic-intro-v3-mov.png",
    "bytes": 7081719
  },
  {
    "title": "d . media cinematic intro v30",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/024-cinematic-intro-d-media-cinematic-intro-v30-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/024-cinematic-intro-d-media-cinematic-intro-v30-mov.png",
    "bytes": 7913916
  },
  {
    "title": "d . media cinematic intro v4",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/025-cinematic-intro-d-media-cinematic-intro-v4-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/025-cinematic-intro-d-media-cinematic-intro-v4-mov.png",
    "bytes": 8726001
  },
  {
    "title": "d . media cinematic intro v5",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/026-cinematic-intro-d-media-cinematic-intro-v5-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/026-cinematic-intro-d-media-cinematic-intro-v5-mov.png",
    "bytes": 3633268
  },
  {
    "title": "d . media cinematic intro v6",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/027-cinematic-intro-d-media-cinematic-intro-v6-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/027-cinematic-intro-d-media-cinematic-intro-v6-mov.png",
    "bytes": 3266792
  },
  {
    "title": "d . media cinematic intro v7",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/028-cinematic-intro-d-media-cinematic-intro-v7-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/028-cinematic-intro-d-media-cinematic-intro-v7-mov.png",
    "bytes": 4411678
  },
  {
    "title": "d . media cinematic intro v8",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/029-cinematic-intro-d-media-cinematic-intro-v8-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/029-cinematic-intro-d-media-cinematic-intro-v8-mov.png",
    "bytes": 8678133
  },
  {
    "title": "d . media cinematic intro v9",
    "category": "Cinematic intro",
    "video": "/optimized-assets/d-media-motion/030-cinematic-intro-d-media-cinematic-intro-v9-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/030-cinematic-intro-d-media-cinematic-intro-v9-mov.png",
    "bytes": 4327884
  },
  {
    "title": "d . media logo intro",
    "category": "Other",
    "video": "/optimized-assets/d-media-motion/031-d-media-logo-intro-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/031-d-media-logo-intro-mov.png",
    "bytes": 3499081
  },
  {
    "title": "d . media logotype intro",
    "category": "Other",
    "video": "/optimized-assets/d-media-motion/032-d-media-logotype-intro-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/032-d-media-logotype-intro-mov.png",
    "bytes": 3169377
  },
  {
    "title": "d . media logo animation v1.01",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/033-logo-animations-d-media-logo-animation-v1-01-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/033-logo-animations-d-media-logo-animation-v1-01-mov.png",
    "bytes": 663630
  },
  {
    "title": "d . media logo animation v1.02",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/034-logo-animations-d-media-logo-animation-v1-02-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/034-logo-animations-d-media-logo-animation-v1-02-mov.png",
    "bytes": 3142023
  },
  {
    "title": "d . media logo animation v1.03",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/035-logo-animations-d-media-logo-animation-v1-03-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/035-logo-animations-d-media-logo-animation-v1-03-mov.png",
    "bytes": 1739578
  },
  {
    "title": "d . media logo animation v1.04",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/036-logo-animations-d-media-logo-animation-v1-04-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/036-logo-animations-d-media-logo-animation-v1-04-mov.png",
    "bytes": 2328228
  },
  {
    "title": "d . media logo animation v1.05",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/037-logo-animations-d-media-logo-animation-v1-05-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/037-logo-animations-d-media-logo-animation-v1-05-mov.png",
    "bytes": 1043379
  },
  {
    "title": "d . media logo animation v1.06",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/038-logo-animations-d-media-logo-animation-v1-06-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/038-logo-animations-d-media-logo-animation-v1-06-mov.png",
    "bytes": 703555
  },
  {
    "title": "d . media logo animation v1.07",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/039-logo-animations-d-media-logo-animation-v1-07-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/039-logo-animations-d-media-logo-animation-v1-07-mov.png",
    "bytes": 1198223
  },
  {
    "title": "d . media logo animation v1.08",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/040-logo-animations-d-media-logo-animation-v1-08-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/040-logo-animations-d-media-logo-animation-v1-08-mov.png",
    "bytes": 1106396
  },
  {
    "title": "d . media logo animation v1.09",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/041-logo-animations-d-media-logo-animation-v1-09-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/041-logo-animations-d-media-logo-animation-v1-09-mov.png",
    "bytes": 2562407
  },
  {
    "title": "d . media logo animation v1.10",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/042-logo-animations-d-media-logo-animation-v1-10-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/042-logo-animations-d-media-logo-animation-v1-10-mov.png",
    "bytes": 1152520
  },
  {
    "title": "d . media logo animation v1.11",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/043-logo-animations-d-media-logo-animation-v1-11-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/043-logo-animations-d-media-logo-animation-v1-11-mov.png",
    "bytes": 534930
  },
  {
    "title": "d . media logo animation v1.12",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/044-logo-animations-d-media-logo-animation-v1-12-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/044-logo-animations-d-media-logo-animation-v1-12-mov.png",
    "bytes": 3718230
  },
  {
    "title": "d . media logo animation v1.13",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/045-logo-animations-d-media-logo-animation-v1-13-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/045-logo-animations-d-media-logo-animation-v1-13-mov.png",
    "bytes": 276098
  },
  {
    "title": "d . media logo animation v1.14",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/046-logo-animations-d-media-logo-animation-v1-14-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/046-logo-animations-d-media-logo-animation-v1-14-mov.png",
    "bytes": 706045
  },
  {
    "title": "d . media logo animation v1.15",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/047-logo-animations-d-media-logo-animation-v1-15-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/047-logo-animations-d-media-logo-animation-v1-15-mov.png",
    "bytes": 2799068
  },
  {
    "title": "d . media logo animation v1.16",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/048-logo-animations-d-media-logo-animation-v1-16-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/048-logo-animations-d-media-logo-animation-v1-16-mov.png",
    "bytes": 1097716
  },
  {
    "title": "d . media logo animation v1.17",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/049-logo-animations-d-media-logo-animation-v1-17-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/049-logo-animations-d-media-logo-animation-v1-17-mov.png",
    "bytes": 1371126
  },
  {
    "title": "d . media logo animation v1.18",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/050-logo-animations-d-media-logo-animation-v1-18-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/050-logo-animations-d-media-logo-animation-v1-18-mov.png",
    "bytes": 603721
  },
  {
    "title": "d . media logo animation v1.19",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/051-logo-animations-d-media-logo-animation-v1-19-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/051-logo-animations-d-media-logo-animation-v1-19-mov.png",
    "bytes": 1382190
  },
  {
    "title": "d . media logo animation v1.20",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/052-logo-animations-d-media-logo-animation-v1-20-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/052-logo-animations-d-media-logo-animation-v1-20-mov.png",
    "bytes": 1264824
  },
  {
    "title": "d . media logo animation v1.21",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/053-logo-animations-d-media-logo-animation-v1-21-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/053-logo-animations-d-media-logo-animation-v1-21-mov.png",
    "bytes": 1114290
  },
  {
    "title": "d . media logo animation v1.22",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/054-logo-animations-d-media-logo-animation-v1-22-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/054-logo-animations-d-media-logo-animation-v1-22-mov.png",
    "bytes": 266394
  },
  {
    "title": "d . media logo animation v1.23",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/055-logo-animations-d-media-logo-animation-v1-23-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/055-logo-animations-d-media-logo-animation-v1-23-mov.png",
    "bytes": 1595169
  },
  {
    "title": "d . media logo animation v1.24",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/056-logo-animations-d-media-logo-animation-v1-24-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/056-logo-animations-d-media-logo-animation-v1-24-mov.png",
    "bytes": 2456511
  },
  {
    "title": "d . media logo animation v1.25",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/057-logo-animations-d-media-logo-animation-v1-25-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/057-logo-animations-d-media-logo-animation-v1-25-mov.png",
    "bytes": 523277
  },
  {
    "title": "d . media logo animation v1.26",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/058-logo-animations-d-media-logo-animation-v1-26-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/058-logo-animations-d-media-logo-animation-v1-26-mov.png",
    "bytes": 1007674
  },
  {
    "title": "d . media logo animation v1.27",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/059-logo-animations-d-media-logo-animation-v1-27-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/059-logo-animations-d-media-logo-animation-v1-27-mov.png",
    "bytes": 2886352
  },
  {
    "title": "d . media logo animation v1.28",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/060-logo-animations-d-media-logo-animation-v1-28-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/060-logo-animations-d-media-logo-animation-v1-28-mov.png",
    "bytes": 1007202
  },
  {
    "title": "d . media logo animation v1.29",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/061-logo-animations-d-media-logo-animation-v1-29-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/061-logo-animations-d-media-logo-animation-v1-29-mov.png",
    "bytes": 793326
  },
  {
    "title": "d . media logo animation v1.30",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/062-logo-animations-d-media-logo-animation-v1-30-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/062-logo-animations-d-media-logo-animation-v1-30-mov.png",
    "bytes": 2355141
  },
  {
    "title": "d . media logo animation v2.01",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/063-logo-animations-d-media-logo-animation-v2-01-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/063-logo-animations-d-media-logo-animation-v2-01-mov.png",
    "bytes": 347400
  },
  {
    "title": "d . media logo animation v2.02",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/064-logo-animations-d-media-logo-animation-v2-02-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/064-logo-animations-d-media-logo-animation-v2-02-mov.png",
    "bytes": 516649
  },
  {
    "title": "d . media logo animation v2.03",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/065-logo-animations-d-media-logo-animation-v2-03-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/065-logo-animations-d-media-logo-animation-v2-03-mov.png",
    "bytes": 1022624
  },
  {
    "title": "d . media logo animation v2.04",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/066-logo-animations-d-media-logo-animation-v2-04-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/066-logo-animations-d-media-logo-animation-v2-04-mov.png",
    "bytes": 1364457
  },
  {
    "title": "d . media logo animation v2.05",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/067-logo-animations-d-media-logo-animation-v2-05-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/067-logo-animations-d-media-logo-animation-v2-05-mov.png",
    "bytes": 6602636
  },
  {
    "title": "d . media logo animation v2.06",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/068-logo-animations-d-media-logo-animation-v2-06-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/068-logo-animations-d-media-logo-animation-v2-06-mov.png",
    "bytes": 861243
  },
  {
    "title": "d . media logo animation v2.07",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/069-logo-animations-d-media-logo-animation-v2-07-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/069-logo-animations-d-media-logo-animation-v2-07-mov.png",
    "bytes": 1239939
  },
  {
    "title": "d . media logo animation v2.08",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/070-logo-animations-d-media-logo-animation-v2-08-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/070-logo-animations-d-media-logo-animation-v2-08-mov.png",
    "bytes": 2680589
  },
  {
    "title": "d . media logo animation v2.09",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/071-logo-animations-d-media-logo-animation-v2-09-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/071-logo-animations-d-media-logo-animation-v2-09-mov.png",
    "bytes": 1355478
  },
  {
    "title": "d . media logo animation v2.10",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/072-logo-animations-d-media-logo-animation-v2-10-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/072-logo-animations-d-media-logo-animation-v2-10-mov.png",
    "bytes": 314984
  },
  {
    "title": "d . media logo animation v2.11",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/073-logo-animations-d-media-logo-animation-v2-11-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/073-logo-animations-d-media-logo-animation-v2-11-mov.png",
    "bytes": 931204
  },
  {
    "title": "d . media logo animation v2.12",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/074-logo-animations-d-media-logo-animation-v2-12-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/074-logo-animations-d-media-logo-animation-v2-12-mov.png",
    "bytes": 341671
  },
  {
    "title": "d . media logo animation v2.13",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/075-logo-animations-d-media-logo-animation-v2-13-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/075-logo-animations-d-media-logo-animation-v2-13-mov.png",
    "bytes": 681703
  },
  {
    "title": "d . media logo animation v2.14",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/076-logo-animations-d-media-logo-animation-v2-14-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/076-logo-animations-d-media-logo-animation-v2-14-mov.png",
    "bytes": 398132
  },
  {
    "title": "d . media logo animation v2.15",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/077-logo-animations-d-media-logo-animation-v2-15-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/077-logo-animations-d-media-logo-animation-v2-15-mov.png",
    "bytes": 2302047
  },
  {
    "title": "d . media logo animation v2.16",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/078-logo-animations-d-media-logo-animation-v2-16-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/078-logo-animations-d-media-logo-animation-v2-16-mov.png",
    "bytes": 1789376
  },
  {
    "title": "d . media logo animation v2.17",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/079-logo-animations-d-media-logo-animation-v2-17-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/079-logo-animations-d-media-logo-animation-v2-17-mov.png",
    "bytes": 4506758
  },
  {
    "title": "d . media logo animation v2.18",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/080-logo-animations-d-media-logo-animation-v2-18-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/080-logo-animations-d-media-logo-animation-v2-18-mov.png",
    "bytes": 2804308
  },
  {
    "title": "d . media logo animation v2.19",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/081-logo-animations-d-media-logo-animation-v2-19-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/081-logo-animations-d-media-logo-animation-v2-19-mov.png",
    "bytes": 1124967
  },
  {
    "title": "d . media logo animation v2.20",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/082-logo-animations-d-media-logo-animation-v2-20-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/082-logo-animations-d-media-logo-animation-v2-20-mov.png",
    "bytes": 825887
  },
  {
    "title": "d . media logo animation v2.21",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/083-logo-animations-d-media-logo-animation-v2-21-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/083-logo-animations-d-media-logo-animation-v2-21-mov.png",
    "bytes": 573303
  },
  {
    "title": "d . media logo animation v2.22",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/084-logo-animations-d-media-logo-animation-v2-22-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/084-logo-animations-d-media-logo-animation-v2-22-mov.png",
    "bytes": 2867465
  },
  {
    "title": "d . media logo animation v2.23",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/085-logo-animations-d-media-logo-animation-v2-23-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/085-logo-animations-d-media-logo-animation-v2-23-mov.png",
    "bytes": 275940
  },
  {
    "title": "d . media logo animation v2.24",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/086-logo-animations-d-media-logo-animation-v2-24-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/086-logo-animations-d-media-logo-animation-v2-24-mov.png",
    "bytes": 592066
  },
  {
    "title": "d . media logo animation v2.25",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/087-logo-animations-d-media-logo-animation-v2-25-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/087-logo-animations-d-media-logo-animation-v2-25-mov.png",
    "bytes": 1002563
  },
  {
    "title": "d . media logo animation v2.26",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/088-logo-animations-d-media-logo-animation-v2-26-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/088-logo-animations-d-media-logo-animation-v2-26-mov.png",
    "bytes": 5877436
  },
  {
    "title": "d . media logo animation v2.27",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/089-logo-animations-d-media-logo-animation-v2-27-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/089-logo-animations-d-media-logo-animation-v2-27-mov.png",
    "bytes": 963175
  },
  {
    "title": "d . media logo animation v2.28",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/090-logo-animations-d-media-logo-animation-v2-28-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/090-logo-animations-d-media-logo-animation-v2-28-mov.png",
    "bytes": 4993240
  },
  {
    "title": "d . media logo animation v2.29",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/091-logo-animations-d-media-logo-animation-v2-29-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/091-logo-animations-d-media-logo-animation-v2-29-mov.png",
    "bytes": 940039
  },
  {
    "title": "d . media logo animation v3.01",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/092-logo-animations-d-media-logo-animation-v3-01-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/092-logo-animations-d-media-logo-animation-v3-01-mov.png",
    "bytes": 748860
  },
  {
    "title": "d . media logo animation v3.02",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/093-logo-animations-d-media-logo-animation-v3-02-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/093-logo-animations-d-media-logo-animation-v3-02-mov.png",
    "bytes": 3321961
  },
  {
    "title": "d . media logo animation v3.03",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/094-logo-animations-d-media-logo-animation-v3-03-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/094-logo-animations-d-media-logo-animation-v3-03-mov.png",
    "bytes": 3751817
  },
  {
    "title": "d . media logo animation v3.04",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/095-logo-animations-d-media-logo-animation-v3-04-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/095-logo-animations-d-media-logo-animation-v3-04-mov.png",
    "bytes": 1106636
  },
  {
    "title": "d . media logo animation v3.05",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/096-logo-animations-d-media-logo-animation-v3-05-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/096-logo-animations-d-media-logo-animation-v3-05-mov.png",
    "bytes": 1851830
  },
  {
    "title": "d . media logo animation v3.06",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/097-logo-animations-d-media-logo-animation-v3-06-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/097-logo-animations-d-media-logo-animation-v3-06-mov.png",
    "bytes": 1550349
  },
  {
    "title": "d . media logo animation v3.07",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/098-logo-animations-d-media-logo-animation-v3-07-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/098-logo-animations-d-media-logo-animation-v3-07-mov.png",
    "bytes": 2010337
  },
  {
    "title": "d . media logo animation v3.08",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/099-logo-animations-d-media-logo-animation-v3-08-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/099-logo-animations-d-media-logo-animation-v3-08-mov.png",
    "bytes": 1033244
  },
  {
    "title": "d . media logo animation v3.09",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/100-logo-animations-d-media-logo-animation-v3-09-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/100-logo-animations-d-media-logo-animation-v3-09-mov.png",
    "bytes": 897744
  },
  {
    "title": "d . media logo animation v3.10",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/101-logo-animations-d-media-logo-animation-v3-10-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/101-logo-animations-d-media-logo-animation-v3-10-mov.png",
    "bytes": 523222
  },
  {
    "title": "d . media logo animation v3.11",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/102-logo-animations-d-media-logo-animation-v3-11-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/102-logo-animations-d-media-logo-animation-v3-11-mov.png",
    "bytes": 3313029
  },
  {
    "title": "d . media logo animation v3.12",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/103-logo-animations-d-media-logo-animation-v3-12-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/103-logo-animations-d-media-logo-animation-v3-12-mov.png",
    "bytes": 3681897
  },
  {
    "title": "d . media logo animation v3.13",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/104-logo-animations-d-media-logo-animation-v3-13-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/104-logo-animations-d-media-logo-animation-v3-13-mov.png",
    "bytes": 2022571
  },
  {
    "title": "d . media logo animation v3.14",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/105-logo-animations-d-media-logo-animation-v3-14-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/105-logo-animations-d-media-logo-animation-v3-14-mov.png",
    "bytes": 1226045
  },
  {
    "title": "d . media logo animation v3.15",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/106-logo-animations-d-media-logo-animation-v3-15-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/106-logo-animations-d-media-logo-animation-v3-15-mov.png",
    "bytes": 1915860
  },
  {
    "title": "d . media logo animation v3.16",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/107-logo-animations-d-media-logo-animation-v3-16-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/107-logo-animations-d-media-logo-animation-v3-16-mov.png",
    "bytes": 6377709
  },
  {
    "title": "d . media logo animation v3.17",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/108-logo-animations-d-media-logo-animation-v3-17-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/108-logo-animations-d-media-logo-animation-v3-17-mov.png",
    "bytes": 3033500
  },
  {
    "title": "d . media logo animation v3.18",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/109-logo-animations-d-media-logo-animation-v3-18-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/109-logo-animations-d-media-logo-animation-v3-18-mov.png",
    "bytes": 327923
  },
  {
    "title": "d . media logo animation v3.19",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/110-logo-animations-d-media-logo-animation-v3-19-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/110-logo-animations-d-media-logo-animation-v3-19-mov.png",
    "bytes": 1351590
  },
  {
    "title": "d . media logo animation v3.20",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/111-logo-animations-d-media-logo-animation-v3-20-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/111-logo-animations-d-media-logo-animation-v3-20-mov.png",
    "bytes": 5425019
  },
  {
    "title": "d . media logo animation v3.21",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/112-logo-animations-d-media-logo-animation-v3-21-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/112-logo-animations-d-media-logo-animation-v3-21-mov.png",
    "bytes": 7930410
  },
  {
    "title": "d . media logo animation v3.22",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/113-logo-animations-d-media-logo-animation-v3-22-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/113-logo-animations-d-media-logo-animation-v3-22-mov.png",
    "bytes": 1524763
  },
  {
    "title": "d . media logo animation v3.23",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/114-logo-animations-d-media-logo-animation-v3-23-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/114-logo-animations-d-media-logo-animation-v3-23-mov.png",
    "bytes": 6276042
  },
  {
    "title": "d . media logo animation v3.24",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/115-logo-animations-d-media-logo-animation-v3-24-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/115-logo-animations-d-media-logo-animation-v3-24-mov.png",
    "bytes": 2183118
  },
  {
    "title": "d . media logo animation v3.25",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/116-logo-animations-d-media-logo-animation-v3-25-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/116-logo-animations-d-media-logo-animation-v3-25-mov.png",
    "bytes": 6788099
  },
  {
    "title": "d . media logo animation v3.26",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/117-logo-animations-d-media-logo-animation-v3-26-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/117-logo-animations-d-media-logo-animation-v3-26-mov.png",
    "bytes": 2030230
  },
  {
    "title": "d . media logo animation v3.27",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/118-logo-animations-d-media-logo-animation-v3-27-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/118-logo-animations-d-media-logo-animation-v3-27-mov.png",
    "bytes": 978798
  },
  {
    "title": "d . media logo animation v3.28",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/119-logo-animations-d-media-logo-animation-v3-28-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/119-logo-animations-d-media-logo-animation-v3-28-mov.png",
    "bytes": 5328914
  },
  {
    "title": "d . media logo animation v3.29",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/120-logo-animations-d-media-logo-animation-v3-29-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/120-logo-animations-d-media-logo-animation-v3-29-mov.png",
    "bytes": 2434519
  },
  {
    "title": "d . media logo animation v3.30",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/121-logo-animations-d-media-logo-animation-v3-30-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/121-logo-animations-d-media-logo-animation-v3-30-mov.png",
    "bytes": 1433763
  },
  {
    "title": "d . media logo animation v4.01",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/122-logo-animations-d-media-logo-animation-v4-01-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/122-logo-animations-d-media-logo-animation-v4-01-mov.png",
    "bytes": 4629824
  },
  {
    "title": "d . media logo animation v4.02",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/123-logo-animations-d-media-logo-animation-v4-02-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/123-logo-animations-d-media-logo-animation-v4-02-mov.png",
    "bytes": 7260636
  },
  {
    "title": "d . media logo animation v4.03",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/124-logo-animations-d-media-logo-animation-v4-03-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/124-logo-animations-d-media-logo-animation-v4-03-mov.png",
    "bytes": 1249856
  },
  {
    "title": "d . media logo animation v4.04",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/125-logo-animations-d-media-logo-animation-v4-04-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/125-logo-animations-d-media-logo-animation-v4-04-mov.png",
    "bytes": 7628787
  },
  {
    "title": "d . media logo animation v4.05",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/126-logo-animations-d-media-logo-animation-v4-05-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/126-logo-animations-d-media-logo-animation-v4-05-mov.png",
    "bytes": 4238861
  },
  {
    "title": "d . media logo animation v4.06",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/127-logo-animations-d-media-logo-animation-v4-06-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/127-logo-animations-d-media-logo-animation-v4-06-mov.png",
    "bytes": 1707891
  },
  {
    "title": "d . media logo animation v4.07",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/128-logo-animations-d-media-logo-animation-v4-07-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/128-logo-animations-d-media-logo-animation-v4-07-mov.png",
    "bytes": 2923943
  },
  {
    "title": "d . media logo animation v4.08",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/129-logo-animations-d-media-logo-animation-v4-08-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/129-logo-animations-d-media-logo-animation-v4-08-mov.png",
    "bytes": 5646636
  },
  {
    "title": "d . media logo animation v4.09",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/130-logo-animations-d-media-logo-animation-v4-09-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/130-logo-animations-d-media-logo-animation-v4-09-mov.png",
    "bytes": 6926637
  },
  {
    "title": "d . media logo animation v4.10",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/131-logo-animations-d-media-logo-animation-v4-10-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/131-logo-animations-d-media-logo-animation-v4-10-mov.png",
    "bytes": 4933150
  },
  {
    "title": "d . media logo animation v4.11",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/132-logo-animations-d-media-logo-animation-v4-11-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/132-logo-animations-d-media-logo-animation-v4-11-mov.png",
    "bytes": 7007134
  },
  {
    "title": "d . media logo animation v4.12",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/133-logo-animations-d-media-logo-animation-v4-12-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/133-logo-animations-d-media-logo-animation-v4-12-mov.png",
    "bytes": 7221863
  },
  {
    "title": "d . media logo animation v4.13",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/134-logo-animations-d-media-logo-animation-v4-13-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/134-logo-animations-d-media-logo-animation-v4-13-mov.png",
    "bytes": 4073103
  },
  {
    "title": "d . media logo animation v4.14",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/135-logo-animations-d-media-logo-animation-v4-14-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/135-logo-animations-d-media-logo-animation-v4-14-mov.png",
    "bytes": 3470671
  },
  {
    "title": "d . media logo animation v4.15",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/136-logo-animations-d-media-logo-animation-v4-15-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/136-logo-animations-d-media-logo-animation-v4-15-mov.png",
    "bytes": 2296074
  },
  {
    "title": "d . media logo animation v4.16",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/137-logo-animations-d-media-logo-animation-v4-16-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/137-logo-animations-d-media-logo-animation-v4-16-mov.png",
    "bytes": 226031
  },
  {
    "title": "d . media logo animation v4.17",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/138-logo-animations-d-media-logo-animation-v4-17-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/138-logo-animations-d-media-logo-animation-v4-17-mov.png",
    "bytes": 3177128
  },
  {
    "title": "d . media logo animation v4.18",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/139-logo-animations-d-media-logo-animation-v4-18-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/139-logo-animations-d-media-logo-animation-v4-18-mov.png",
    "bytes": 2560378
  },
  {
    "title": "d . media logo animation v4.19",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/140-logo-animations-d-media-logo-animation-v4-19-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/140-logo-animations-d-media-logo-animation-v4-19-mov.png",
    "bytes": 5164423
  },
  {
    "title": "d . media logo animation v4.20",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/141-logo-animations-d-media-logo-animation-v4-20-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/141-logo-animations-d-media-logo-animation-v4-20-mov.png",
    "bytes": 1801495
  },
  {
    "title": "d . media logo animation v4.21",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/142-logo-animations-d-media-logo-animation-v4-21-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/142-logo-animations-d-media-logo-animation-v4-21-mov.png",
    "bytes": 4209363
  },
  {
    "title": "d . media logo animation v4.22",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/143-logo-animations-d-media-logo-animation-v4-22-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/143-logo-animations-d-media-logo-animation-v4-22-mov.png",
    "bytes": 2527727
  },
  {
    "title": "d . media logo animation v4.23",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/144-logo-animations-d-media-logo-animation-v4-23-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/144-logo-animations-d-media-logo-animation-v4-23-mov.png",
    "bytes": 5248817
  },
  {
    "title": "d . media logo animation v4.24",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/145-logo-animations-d-media-logo-animation-v4-24-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/145-logo-animations-d-media-logo-animation-v4-24-mov.png",
    "bytes": 612865
  },
  {
    "title": "d . media logo animation v4.25",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/146-logo-animations-d-media-logo-animation-v4-25-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/146-logo-animations-d-media-logo-animation-v4-25-mov.png",
    "bytes": 5168842
  },
  {
    "title": "d . media logo animation v4.26",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/147-logo-animations-d-media-logo-animation-v4-26-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/147-logo-animations-d-media-logo-animation-v4-26-mov.png",
    "bytes": 1583209
  },
  {
    "title": "d . media logo animation v4.27",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/148-logo-animations-d-media-logo-animation-v4-27-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/148-logo-animations-d-media-logo-animation-v4-27-mov.png",
    "bytes": 3352286
  },
  {
    "title": "d . media logo animation v4.28",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/149-logo-animations-d-media-logo-animation-v4-28-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/149-logo-animations-d-media-logo-animation-v4-28-mov.png",
    "bytes": 229980
  },
  {
    "title": "d . media logo animation v4.29",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/150-logo-animations-d-media-logo-animation-v4-29-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/150-logo-animations-d-media-logo-animation-v4-29-mov.png",
    "bytes": 3689329
  },
  {
    "title": "d . media logo animation v4.30",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/151-logo-animations-d-media-logo-animation-v4-30-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/151-logo-animations-d-media-logo-animation-v4-30-mov.png",
    "bytes": 641074
  },
  {
    "title": "d . media logo animation v4.31",
    "category": "Logo animations",
    "video": "/optimized-assets/d-media-motion/152-logo-animations-d-media-logo-animation-v4-31-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/152-logo-animations-d-media-logo-animation-v4-31-mov.png",
    "bytes": 3320100
  },
  {
    "title": "d . media logo intro v1",
    "category": "Logo intro",
    "video": "/optimized-assets/d-media-motion/153-logo-intro-d-media-logo-intro-v1-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/153-logo-intro-d-media-logo-intro-v1-mov.png",
    "bytes": 257121
  },
  {
    "title": "d . media logo intro v2",
    "category": "Logo intro",
    "video": "/optimized-assets/d-media-motion/154-logo-intro-d-media-logo-intro-v2-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/154-logo-intro-d-media-logo-intro-v2-mov.png",
    "bytes": 219671
  },
  {
    "title": "d . media logo intro v3",
    "category": "Logo intro",
    "video": "/optimized-assets/d-media-motion/155-logo-intro-d-media-logo-intro-v3-mov.m4v",
    "poster": "/optimized-assets/d-media-motion/155-logo-intro-d-media-logo-intro-v3-mov.png",
    "bytes": 238747
  }
] as const;
