// Generated by scripts/import-main-project-assets.mjs. Do not edit manually.
export const mainProjectAssetAdditions = {
  "aneliart": [
    {
      "src": "/optimized-assets/project-web/main/aneliart/01-aneliart-logo-black-transparent.webp",
      "label": "AneliArt_logo @ black_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/aneliart/02-aneliart-logo-white-transparent.webp",
      "label": "AneliArt_logo @ white_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/aneliart/03-aneliart-logo-transparent.webp",
      "label": "AneliArt_logo_transparent.png"
    }
  ],
  "boris-lilov-photography": [
    {
      "src": "/optimized-assets/project-web/main/boris-lilov-photography/01-boris-lilov-photography-mockup.webp",
      "label": "boris lilov PHOTOGRAPHY _ mockup.png"
    },
    {
      "src": "/optimized-assets/project-web/main/boris-lilov-photography/02-boris-lilov-photography-logo-transperent.webp",
      "label": "boris lilov PHOTOGRAPHY logo _ transperent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/boris-lilov-photography/03-boris-lilov-photography-logo-logotype-transperent.webp",
      "label": "boris lilov PHOTOGRAPHY logo+logotype _ transperent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/boris-lilov-photography/04-boris-lilov-photography-logotype-transperent.webp",
      "label": "boris lilov PHOTOGRAPHY logotype _ transperent.png"
    }
  ],
  "dj-just-mp": [
    {
      "src": "/optimized-assets/project-web/main/dj-just-mp/01-dj-just-mp-logo-black-transparent.webp",
      "label": "DJ Just MP_logo @ black_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/dj-just-mp/02-dj-just-mp-logo-original-transparent.webp",
      "label": "DJ Just MP_logo @ original_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/dj-just-mp/03-dj-just-mp-logo-white-transparent.webp",
      "label": "DJ Just MP_logo @ white_transparent.png"
    }
  ],
  "dj-nedi": [
    {
      "src": "/optimized-assets/project-web/main/dj-nedi/01-dj-nedi-logo-black-transparent.webp",
      "label": "DJ Nedi_logo @ black_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/dj-nedi/02-dj-nedi-logo-white-transparent.webp",
      "label": "DJ Nedi_logo @ white_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/dj-nedi/03-dynamite-youtube-thumbnail-katya.webp",
      "label": "Dynamite youtube thumbnail +Katya.jpg"
    },
    {
      "src": "/optimized-assets/project-web/main/dj-nedi/04-dynamite-youtube-thumbnail-nedi.webp",
      "label": "Dynamite youtube thumbnail +Nedi.jpg"
    },
    {
      "src": "/optimized-assets/project-web/main/dj-nedi/05-dynamite-youtube-thumbnail-two.webp",
      "label": "Dynamite youtube thumbnail +two.jpg"
    },
    {
      "src": "/optimized-assets/project-web/main/dj-nedi/06-dynamite-cover-transparent.webp",
      "label": "Dynamite_cover_transparent.png"
    }
  ],
  "diana": [
    {
      "src": "/optimized-assets/project-web/main/diana/01-diana-logo-black-transparent.webp",
      "label": "Diana_logo @ black_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/diana/02-diana-logo-original-transparent.webp",
      "label": "Diana_logo @ original_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/diana/03-diana-logo-original-white-type-transparent.webp",
      "label": "Diana_logo @ original_white type_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/diana/04-diana-logo-white-transparent.webp",
      "label": "Diana_logo @ white_transparent.png"
    }
  ],
  "elena-skevov-mua": [
    {
      "src": "/optimized-assets/project-web/main/elena-skevov-mua/01-es-mua-back.webp",
      "label": "ES mua back.jpg"
    },
    {
      "src": "/optimized-assets/project-web/main/elena-skevov-mua/02-es-mua-front.webp",
      "label": "ES mua Front.jpg"
    }
  ],
  "galka-nails": [
    {
      "src": "/optimized-assets/project-web/main/galka-nails/01-galka-s-nails-transperent.webp",
      "label": "Galka’s nails transperent.png"
    }
  ],
  "gosmile": [
    {
      "src": "/optimized-assets/project-web/main/gosmile/01-go-smile-black.webp",
      "label": "Go Smile Black.png"
    },
    {
      "src": "/optimized-assets/project-web/main/gosmile/02-go-smile-white.webp",
      "label": "Go Smile White.png"
    },
    {
      "src": "/optimized-assets/project-web/main/gosmile/03-go-smile-v34-38x38x125.webp",
      "label": "GO SMILE-V34(38x38x125).png"
    }
  ],
  "j-v": [
    {
      "src": "/optimized-assets/project-web/main/j-v/01-j-v-mockup.webp",
      "label": "J & V _ mockup.png"
    },
    {
      "src": "/optimized-assets/project-web/main/j-v/02-j-v.webp",
      "label": "J & V.png"
    }
  ],
  "kdj": [
    {
      "src": "/optimized-assets/project-web/main/kdj/01-kdj-logo-black-transperent.webp",
      "label": "KDJ _ logo _ black _ transperent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/kdj/02-kdj-logo-electric-green-transperent.webp",
      "label": "KDJ _ logo _ electric green _ transperent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/kdj/03-kdj-logo-electric-orange-transperent.webp",
      "label": "KDJ _ logo _ electric orange _ transperent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/kdj/04-kdj-logo-white-transperent.webp",
      "label": "KDJ _ logo _ white _ transperent.png"
    }
  ],
  "mis-18": [
    {
      "src": "/optimized-assets/project-web/main/mis-18/01-mis-18-logo-mockup.webp",
      "label": "MIS 18 logo _ mockup.png"
    },
    {
      "src": "/optimized-assets/project-web/main/mis-18/02-mis-18-logo-transperent.webp",
      "label": "MIS 18 logo _ Transperent.png"
    }
  ],
  "monika-hristova": [
    {
      "src": "/optimized-assets/project-web/main/monika-hristova/01-monika-hristova-bc.webp",
      "label": "Monika Hristova_BC.pdf"
    }
  ],
  "pp-hairstyle": [
    {
      "src": "/optimized-assets/project-web/main/pp-hairstyle/01-pp-hairstyle-logo-transperent.webp",
      "label": "PP hairstyle _ logo _ transperent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/pp-hairstyle/02-pp-hairstyle.webp",
      "label": "PP hairstyle.png"
    }
  ],
  "photo-workshop": [
    {
      "src": "/optimized-assets/project-web/main/photo-workshop/01-photo-workshop-color-transparent-logo.webp",
      "label": "Photo workshop _ color _ transparent _ logo.png"
    },
    {
      "src": "/optimized-assets/project-web/main/photo-workshop/02-photo-workshop-logo.webp",
      "label": "Photo workshop _ logo.png"
    },
    {
      "src": "/optimized-assets/project-web/main/photo-workshop/03-photo-workshop-white-transparent-logo.webp",
      "label": "Photo workshop _ white _ transparent _ logo.png"
    }
  ],
  "plamena-nails": [
    {
      "src": "/optimized-assets/project-web/main/plamena-nails/01-plamena-nails-logo-grey-transperent.webp",
      "label": "Plamena nails _ logo _ grey _ transperent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/plamena-nails/02-plamena-nails-logo-red-transperent.webp",
      "label": "Plamena nails _ logo _ red _ transperent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/plamena-nails/03-plamena-nails-logo-violet-transperent.webp",
      "label": "Plamena nails _ logo _ violet _ transperent.png"
    }
  ],
  "sport-fishing-stoletovo": [
    {
      "src": "/optimized-assets/project-web/main/sport-fishing-stoletovo/01-sfs-black-transperent.webp",
      "label": "SFS_black_transperent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/sport-fishing-stoletovo/02-sfs-mockup.webp",
      "label": "SFS_mockup.png"
    },
    {
      "src": "/optimized-assets/project-web/main/sport-fishing-stoletovo/03-sfs-original.webp",
      "label": "SFS_original.png"
    },
    {
      "src": "/optimized-assets/project-web/main/sport-fishing-stoletovo/04-sfs-orignal-transperent.webp",
      "label": "SFS_orignal_transperent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/sport-fishing-stoletovo/05-sfs-white-transperent.webp",
      "label": "SFS_white_transperent.png"
    }
  ],
  "stanulovi-s-house": [
    {
      "src": "/optimized-assets/project-web/main/stanulovi-s-house/01-stanulovi-01-01.webp",
      "label": "Stanulovi-01-01.png"
    }
  ],
  "support-account": [
    {
      "src": "/optimized-assets/project-web/main/support-account/01-support-account-logo-mockup.webp",
      "label": "Support Account_logo mockup.jpg"
    },
    {
      "src": "/optimized-assets/project-web/main/support-account/02-support-account-logo-mockup.webp",
      "label": "Support Account_logo_mockup.png"
    },
    {
      "src": "/optimized-assets/project-web/main/support-account/03-support-account-logo-transparent.webp",
      "label": "Support Account_logo_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/support-account/04-support-account-logotype-mockup.webp",
      "label": "Support Account_logotype_mockup.jpeg"
    },
    {
      "src": "/optimized-assets/project-web/main/support-account/05-support-account-logotype-mockup.webp",
      "label": "Support Account_logotype_mockup.png"
    },
    {
      "src": "/optimized-assets/project-web/main/support-account/06-support-account-logotype-transparent-bulgarian.webp",
      "label": "Support Account_logotype_transparent (bulgarian).png"
    },
    {
      "src": "/optimized-assets/project-web/main/support-account/07-support-account-logotype-transparent-original.webp",
      "label": "Support Account_logotype_transparent (original).png"
    }
  ],
  "support-account-group": [
    {
      "src": "/optimized-assets/project-web/main/support-account-group/01-support-account-group-logo-mockup.webp",
      "label": "Support Account Group_logo_mockup.jpg"
    },
    {
      "src": "/optimized-assets/project-web/main/support-account-group/02-support-account-group-logo-white-background.webp",
      "label": "Support Account Group_logo_white background.png"
    },
    {
      "src": "/optimized-assets/project-web/main/support-account-group/03-support-account-group-logotype-mockup.webp",
      "label": "Support Account Group_logotype mockup.jpg"
    },
    {
      "src": "/optimized-assets/project-web/main/support-account-group/04-support-account-group-logotype-transparent.webp",
      "label": "Support Account Group_logotype_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/support-account-group/05-support-account-group-transparent.webp",
      "label": "Support Account Group_transparent.png"
    }
  ],
  "tanev-car-detailing": [
    {
      "src": "/optimized-assets/project-web/main/tanev-car-detailing/01-tanev-cds-logo-black-transparent.webp",
      "label": "TANEV CDS_logo @ black_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/tanev-car-detailing/02-tanev-cds-logo-white-transparent.webp",
      "label": "TANEV CDS_logo @ white_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/tanev-car-detailing/03-tanev-cds-logo-transparent.webp",
      "label": "TANEV CDS_logo_transparent.png"
    }
  ],
  "ts-makeup": [
    {
      "src": "/optimized-assets/project-web/main/ts-makeup/01-ts-makeup-logo-lasercut-trasperent.webp",
      "label": "TS makeup _ logo _ lasercut _ trasperent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/ts-makeup/02-ts-makeup-logo-transperent-shadow.webp",
      "label": "TS makeup _ logo _ transperent _ +shadow.png"
    }
  ],
  "yanita": [
    {
      "src": "/optimized-assets/project-web/main/yanita/01-yanita-gift-card-copy.webp",
      "label": "YANITA gift card copy.png"
    },
    {
      "src": "/optimized-assets/project-web/main/yanita/02-yanita-gift-card.webp",
      "label": "YANITA gift card.png"
    },
    {
      "src": "/optimized-assets/project-web/main/yanita/03-yanita-logo-black-transparent.webp",
      "label": "Yanita_logo @ black_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/yanita/04-yanita-logo-original-transparent.webp",
      "label": "Yanita_logo @ original_transparent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/yanita/05-yanita-logo-white-transparent.webp",
      "label": "Yanita_logo @ white_transparent.png"
    }
  ],
  "enduro-team-stoletovo": [
    {
      "src": "/optimized-assets/project-web/main/enduro-team-stoletovo/01-enduro-team-stoletovo-transperent.webp",
      "label": "enduro team STOLETOVO (transperent).png"
    }
  ],
  "makeup-by-tsvetomira": [
    {
      "src": "/optimized-assets/project-web/main/makeup-by-tsvetomira/01-make-up-by-tsvetomira-work-logo-transperent.webp",
      "label": "make up by Tsvetomira work logo _ transperent.png"
    },
    {
      "src": "/optimized-assets/project-web/main/makeup-by-tsvetomira/02-make-up-by-tsvetomira-work-logo.webp",
      "label": "make up by Tsvetomira work logo.jpg"
    },
    {
      "src": "/optimized-assets/project-web/main/makeup-by-tsvetomira/03-makeup-by-tsvetomira-bussines-card-v1.webp",
      "label": "MakeUp by Tsvetomira - Bussines card v1.jpg"
    },
    {
      "src": "/optimized-assets/project-web/main/makeup-by-tsvetomira/04-makeup-by-tsvetomira-bussines-card-v2.webp",
      "label": "MakeUp by Tsvetomira - Bussines card v2.jpg"
    },
    {
      "src": "/optimized-assets/project-web/main/makeup-by-tsvetomira/05-makeup-by-tsvetomira-woman-stuff-mockup.webp",
      "label": "MakeUp by Tsvetomira woman stuff_mockup.jpg"
    }
  ],
  "syanka-ot-minaloto": [
    {
      "src": "/optimized-assets/project-web/main/syanka-ot-minaloto/01-1-thumbnail.webp",
      "label": "Сянка от миналото - епизод 1_thumbnail.png"
    },
    {
      "src": "/optimized-assets/project-web/main/syanka-ot-minaloto/02-2-thumbnail.webp",
      "label": "Сянка от миналото - епизод 2_thumbnail.png"
    },
    {
      "src": "/optimized-assets/project-web/main/syanka-ot-minaloto/03-3-thumbnail.webp",
      "label": "Сянка от миналото - епизод 3_thumbnail.png"
    },
    {
      "src": "/optimized-assets/project-web/main/syanka-ot-minaloto/04-4-thumbnail.webp",
      "label": "Сянка от миналото - епизод 4_thumbnail.png"
    },
    {
      "src": "/optimized-assets/project-web/main/syanka-ot-minaloto/05-5-thumbnail.webp",
      "label": "Сянка от миналото - епизод 5_thumbnail.png"
    },
    {
      "src": "/optimized-assets/project-web/main/syanka-ot-minaloto/06-6-thumbnail.webp",
      "label": "Сянка от миналото - епизод 6_thumbnail.png"
    },
    {
      "src": "/optimized-assets/project-web/main/syanka-ot-minaloto/07-1-thumbnail.webp",
      "label": "Сянка от миналото - сезон 1_thumbnail.png"
    },
    {
      "src": "/optimized-assets/project-web/main/syanka-ot-minaloto/08-facebook-cover.webp",
      "label": "Сянка от миналото (Facebook Cover).png"
    },
    {
      "src": "/optimized-assets/project-web/main/syanka-ot-minaloto/09-logo-no-txt-white-background.webp",
      "label": "Сянка от миналото_logo_no txt_white background.png"
    },
    {
      "src": "/optimized-assets/project-web/main/syanka-ot-minaloto/10-logo-white-background.webp",
      "label": "Сянка от миналото_logo_white background.png"
    },
    {
      "src": "/optimized-assets/project-web/main/syanka-ot-minaloto/11-mockup.webp",
      "label": "Сянка от миналото_mockup.png"
    },
    {
      "src": "/optimized-assets/project-web/main/syanka-ot-minaloto/12-asset.webp",
      "label": "Сянка от миналото.png"
    }
  ],
  "teti": [
    {
      "src": "/optimized-assets/project-web/main/teti/01-salon-business-cards-1.webp",
      "label": "salon business cards-1.png"
    },
    {
      "src": "/optimized-assets/project-web/main/teti/02-salon-business-cards-2.webp",
      "label": "salon business cards-2.png"
    },
    {
      "src": "/optimized-assets/project-web/main/teti/03-salon-business-cards-3.webp",
      "label": "salon business cards-3.png"
    },
    {
      "src": "/optimized-assets/project-web/main/teti/04-salon-business-cards-4.webp",
      "label": "salon business cards-4.png"
    },
    {
      "src": "/optimized-assets/project-web/main/teti/05-salon-prices.webp",
      "label": "salon prices.png"
    },
    {
      "src": "/optimized-assets/project-web/main/teti/06-salon-working-time.webp",
      "label": "salon working time.png"
    }
  ]
} as const;

export const mainProjectArchiveEntries = [
  {
    "slug": "elena-skevov-mua",
    "title": "Elena Skevov MUA",
    "imageCount": 2,
    "cover": "/optimized-assets/project-web/main/elena-skevov-mua/01-es-mua-back.webp",
    "images": [
      {
        "src": "/optimized-assets/project-web/main/elena-skevov-mua/01-es-mua-back.webp",
        "label": "ES mua back.jpg"
      },
      {
        "src": "/optimized-assets/project-web/main/elena-skevov-mua/02-es-mua-front.webp",
        "label": "ES mua Front.jpg"
      }
    ],
    "featured": false,
    "priority": 999,
    "summary": "Проект от основния архив на d . media, добавен с наличните оригинални файлове и приложни материали.",
    "context": "Архивът показва наличните файлове за Elena Skevov MUA, подготвени като леки web изображения за бързо разглеждане в сайта.",
    "focus": [
      "Оригинални файлове от проектната папка",
      "Оптимизирани web версии за сайта",
      "Преглед на наличните приложения и работни материали"
    ]
  },
  {
    "slug": "monika-hristova",
    "title": "Monika Hristova",
    "imageCount": 1,
    "cover": "/optimized-assets/project-web/main/monika-hristova/01-monika-hristova-bc.webp",
    "images": [
      {
        "src": "/optimized-assets/project-web/main/monika-hristova/01-monika-hristova-bc.webp",
        "label": "Monika Hristova_BC.pdf"
      }
    ],
    "featured": false,
    "priority": 999,
    "summary": "Проект от основния архив на d . media, добавен с наличните оригинални файлове и приложни материали.",
    "context": "Архивът показва наличните файлове за Monika Hristova, подготвени като леки web изображения за бързо разглеждане в сайта.",
    "focus": [
      "Оригинални файлове от проектната папка",
      "Оптимизирани web версии за сайта",
      "Преглед на наличните приложения и работни материали"
    ]
  },
  {
    "slug": "teti",
    "title": "Тети",
    "imageCount": 6,
    "cover": "/optimized-assets/project-web/main/teti/01-salon-business-cards-1.webp",
    "images": [
      {
        "src": "/optimized-assets/project-web/main/teti/01-salon-business-cards-1.webp",
        "label": "salon business cards-1.png"
      },
      {
        "src": "/optimized-assets/project-web/main/teti/02-salon-business-cards-2.webp",
        "label": "salon business cards-2.png"
      },
      {
        "src": "/optimized-assets/project-web/main/teti/03-salon-business-cards-3.webp",
        "label": "salon business cards-3.png"
      },
      {
        "src": "/optimized-assets/project-web/main/teti/04-salon-business-cards-4.webp",
        "label": "salon business cards-4.png"
      },
      {
        "src": "/optimized-assets/project-web/main/teti/05-salon-prices.webp",
        "label": "salon prices.png"
      },
      {
        "src": "/optimized-assets/project-web/main/teti/06-salon-working-time.webp",
        "label": "salon working time.png"
      }
    ],
    "featured": false,
    "priority": 999,
    "summary": "Проект от основния архив на d . media, добавен с наличните оригинални файлове и приложни материали.",
    "context": "Архивът показва наличните файлове за Тети, подготвени като леки web изображения за бързо разглеждане в сайта.",
    "focus": [
      "Оригинални файлове от проектната папка",
      "Оптимизирани web версии за сайта",
      "Преглед на наличните приложения и работни материали"
    ]
  }
] as const;
