// Generated by scripts/import-old-flyers.mjs. Do not edit manually.
export const oldFlyerItems = [
  {
    "src": "/optimized-assets/project-web/old-flyers/01-05apr-addicted-to-music-h.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/02-12jan-music-addiction.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/03-22-23dec-opium-night-bar.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/04-27500177-794592694066491-3836290634886429689-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/05-27dec-rnb-2.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/06-53833614-1056930751166016-7592783103018401792-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/07-addicted-to-music.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/08-nye-flyer-2.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/09-107002821-1446063095586111-1196357620216319641-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/10-116248566-1464818747043879-197896797622091824-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/11-116279979-1464818833710537-9003995300917157720-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/12-116336271-1464818607043893-1824703713105556744-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/13-15-04-2019.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/14-2019-07-17-rnb-bg.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/15-2019-12-25-xmas-party-opium.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/16-2019-12-26-birthday-party-opium.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/17-2020-02-01-dj-nedi.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/18-2020-06-06-dj-nedi.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/19-2020-08-07-promotion-friday.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/20-2020-08-08-summer-dj-party.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/21-27710209-798094080383019-4731082054730102080-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/22-3-4-aug-addicted-to-house.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/23-56520114-1068402960018795-6051968636459941888-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/24-60310930-1090173211175103-7391650768094232576-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/25-67483722-1144429902416100-1368616278335422464-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/26-67694136-1154080354784388-8053871717967200256-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/27-67745033-1154080368117720-8454092292620288000-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/28-68892844-1168216353370788-5684091738231144448-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/29-84665839-1340075802851508-1165482703399682048-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/30-86184190-1319014801624275-66699051105517568-o.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/31-bg-vs-popfolk.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/32-dj-party-red-yellow.webp",
    "alt": "Архивен флаер от ранни години"
  },
  {
    "src": "/optimized-assets/project-web/old-flyers/33-grand-opening-phoenix-vertical-final.webp",
    "alt": "Архивен флаер от ранни години"
  }
] as const;
