import type { Locale } from "@/lib/i18n";

const pageCopy = {
  bg: {
    seo: {
      siteDescription:
        "В d . media създаваме бранд идентичност, съдържание, графичен дизайн и реклама за реално приложение от студио в София, България.",
      siteKeywords: [
        "d . media",
        "бранд идентичност",
        "създаване на бранд идентичност",
        "създаване на съдържание",
        "управление на социални медии",
        "графичен дизайн",
        "реклама",
        "дизайн студио",
        "маркетинг материали",
        "София",
      ],
    },
    home: {
      metaTitle: "Бранд идентичност, съдържание, дизайн и реклама",
      metaDescription:
        "d . media е студио в София за бранд идентичност, съдържание, дизайн и реклама с фокус върху реално приложение.",
      eyebrow: "Ясен облик. Подредена комуникация. Реално приложение.",
      brandmarkAlt: "Брандмарк на d . media",
      title: "Създаваме бранд идентичност, съдържание, дизайн и реклама в една работеща система.",
      text: "Работим за бизнеси, които търсят ясен облик, подредена комуникация и материали за реална употреба. От знака до ежедневната комуникация, всичко се изгражда в една последователна система.",
      note: "Ясен облик. Подреден процес. Последователно приложение.",
      primaryCta: "Изпрати проектно запитване",
      secondaryCta: "Разгледай услугите",
      servicesEyebrow: "услуги",
      servicesTitle: "Четири основни решения. Един подреден обхват.",
      servicesCta: "Изпрати кратък проектен контекст",
      pricingEyebrow: "начални рамки",
      pricingTitle: "Начални рамки за стартов обхват.",
      pricingText: "Показваме входни рамки за най-честите стартови обхвати. Те дават ориентир за типичен старт, а финалният обхват се подрежда според проекта.",
      pricingRangeCue:
        "Това са начални рамки за стартов обхват, не списък с единични изпълнения.",
      pricingItems: [
        {
          title: "Стартов пакет за визуална идентичност",
          price: "от 700 € (1369,08 лв.)",
          value: "лого, логотип и основни правила за подредено първо приложение",
        },
        {
          title: "Стартов social пакет",
          price: "от 25 € (48,90 лв.)",
          value: "базова визия и текстов ред за работещо първо присъствие",
        },
        {
          title: "Стартов печатен пакет",
          price: "от 25 € (48,90 лв.)",
          value: "първи печатен материал, подготвен чисто за реална употреба",
        },
        {
          title: "Стартов motion пакет",
          price: "от 50 € (97,79 лв.)",
          value: "кратък motion или видео asset за подредено първо използване",
        },
      ],
      pricingNote:
        "Цените в лева са преизчислени по официалния фиксиран курс на БНБ съгласно закона за въвеждане на еврото.",
      pricingSecondaryNote:
        "Подробният ценоразпис е наличен при запитване. Началният обхват се уточнява според нужните формати, обем и сложност.",
      pricingCta: "Изпрати проектно запитване",
      processEyebrow: "процес",
      processTitle: "Ясен процес. Подреден работен ред.",
      processCta: "Започни с кратък контекст",
      projectsEyebrow: "проекти",
      projectsTitle: "Подбрана работа с реално приложение.",
      projectsText:
        "Идентичности, формати и материали, разработени за конкретни брандове и подготвени за реална работа след проекта.",
      projectsCta: "Разгледай подбраните проекти",
      aboutEyebrow: "за бранда",
      aboutTitle: "Работим със система, ред и реално приложение.",
      aboutCta: "Изпрати проектен контекст",
      contactEyebrow: "следваща стъпка",
      contactTitle: "Ако обхватът е ясен, продължаваме оттук.",
      contactText: "Изпрати проектен контекст и ще върнем обхват, срок и следваща стъпка според задачата.",
      contactPrimaryCta: "Изпрати проектен контекст",
      contactSecondaryCta: "Разгледай услугите",
    },
    services: {
      metaTitle: "Услуги",
      metaDescription:
        "Услуги на d . media за бранд идентичност, съдържание, графичен дизайн и реклама от студио в София.",
      eyebrow: "услуги",
      title: "Услуги за бранд, съдържание и работещо присъствие.",
      text: "Тук е работният обхват. Всяка услуга е подредена така, че да води до ясен deliverable и готовност за реална употреба.",
      includes: "Какво включва",
      audience: "За кого е",
      result: "Какъв резултат дава",
      ctaEyebrow: "следваща стъпка",
      ctaTitle: "Когато контекстът е ясен, работата тръгва подредено.",
      ctaText: "Изпрати проектен контекст, нужда и срок. Оттам подреждаме обхвата, цената и следващата стъпка.",
      primaryCta: "Изпрати проектен контекст",
      secondaryCta: "Разгледай проектите",
    },
    projects: {
      metaTitle: "Проекти",
      metaDescription:
        "Разгледай проекти на d . media с бранд идентичност, дизайн, съдържание и реални файлове от завършена работа.",
      eyebrow: "проекти",
      title: "Подбрана работа с реално приложение.",
      text: "Тук е работата, която показва най-ясно начина на мислене, нивото на изпълнение и приложението след проекта.",
      readingTitle: "Какво ще видиш",
      readingText: "Идентичности, визии и формати, разработени за реална среда.",
      resultTitle: "Какво остава след проекта",
      resultText: "Подредени assets, които могат да се използват веднага и последователно.",
      selectedEyebrow: "подбран избор",
      selectedTitle: "Избрани проекти",
      selectedText: "Това е подбраната работа, която най-ясно показва нивото, посоката и приложението след проекта.",
      archiveEyebrow: "архив",
      archiveTitle: "Архив на реализациите",
      archiveText:
        "Архивът събира останалите реализации и показва обхвата на натрупаната работа, без да ги поставя в същата роля като подбраните проекти.",
      legacyEyebrow: "архивни колекции",
      ctaEyebrow: "следваща стъпка",
      ctaTitle: "Ако търсиш такава яснота, започни оттук.",
      ctaText: "Изпрати кратък проектен контекст, какво трябва да се изработи и какъв резултат очакваш. Оттам подреждаме обхвата и следващата стъпка.",
      primaryCta: "Изпрати кратък проектен контекст",
      secondaryCta: "Разгледай услугите",
    },
    projectDetail: {
      eyebrow: "проект",
      context: "Контекст",
      solution: "Решение",
      usage: "Как се използва",
      archive: "Архив",
      meta: "реални файлове от разработката",
      back: "обратно към проектите",
      applicationsEyebrow: "приложения",
      applicationsTitle: "Наличните файлове от този проект.",
      fallbackTitle: "Проект",
    },
    about: {
      metaTitle: "За бранда",
      metaDescription:
        "Научи повече за d . media, начина на работа и достъпа до официалния брандбук на студиото в София.",
      eyebrow: "за бранда",
      text: "d . media е студио, изградено за ясна работа, последователност и реална употреба.",
      brandbookTitle: "Официален брандбук",
      brandbookText:
        "Брандбукът показва основната система, правилата за употреба и начина, по който идентичността се държи последователно.",
      primaryCta: "Изпрати кратък контекст",
      secondaryCta: "Отвори брандбука",
    },
    contact: {
      metaTitle: "Контакт",
      metaDescription:
        "Свържи се с d . media за нов проект по бранд идентичност, съдържание, дизайн или реклама.",
      eyebrow: "контакт",
      title: "Ако имаш проект, започни с ясен контекст.",
      text: "Изпрати какво трябва да се изработи, за кого е, в какъв срок и с какъв приоритет. Връщаме преценка, обхват и следваща стъпка.",
      needsTitle: "Какво да изпратиш",
      needsText:
        "Изпрати услуга, кратък контекст, срок, ориентир за обем и ако има, референции или налични материали.",
      responseTitle: "Какво връщаме",
      responseText:
        "Връщаме отговор с преценка, обхват, срок, цена или нужда от кратко уточнение преди оферта.",
      primaryCta: "Изпрати проектен контекст",
      secondaryCta: "Разгледай услугите",
      mainContact: "Контакт",
      channels: "Канали",
    },
    terms: {
      metaTitle: "Общи условия",
      metaDescription:
        "Прегледай условията на d . media за възлагане, изпълнение, документи, срокове и права по проекта.",
      eyebrow: "условия",
      title: "Общи условия",
      text: "Условия за ползване на услугите на d . media",
      shortLabel: "Кратка версия",
      fullLabel: "Пълна версия",
      shortTitle: "Кратка версия",
      policyTitle: "Пълна версия",
    },
    privacy: {
      metaTitle: "Поверителност",
      metaDescription:
        "Виж как d . media обработва лични данни, на какво основание и какви права имат клиентите.",
      eyebrow: "поверителност",
      title: "Поверителност и защита на личните данни",
      text: "d . media обработва лични данни в съответствие с Регламент (ЕС) 2016/679 (GDPR) и приложимото българско законодателство.",
      full: "Прочети пълната политика",
      policyTitle: "Политика за поверителност",
    },
  },
  en: {
    seo: {
      siteDescription:
        "At d . media, we create brand identity, content, graphic design, and advertising for real application from a studio based in Sofia, Bulgaria.",
      siteKeywords: [
        "d . media",
        "brand identity",
        "brand identity design",
        "content creation",
        "social media management",
        "graphic design",
        "advertising",
        "design studio",
        "marketing materials",
        "Sofia",
      ],
    },
    home: {
      metaTitle: "Brand identity, content, design, and advertising",
      metaDescription:
        "d . media is a Sofia, Bulgaria studio for brand identity, content, design, and advertising built for real application.",
      eyebrow: "Clear presence. Ordered communication. Real application.",
      brandmarkAlt: "d . media brand mark",
      title: "We create brand identity, content, design and advertising in one working system.",
      text: "We work with businesses that need a clear presence, ordered communication, and materials for real use. From mark to day-to-day communication, everything is built as one consistent system.",
      note: "Clear presence. Ordered process. Consistent application.",
      primaryCta: "Send a project inquiry",
      secondaryCta: "Explore services",
      servicesEyebrow: "services",
      servicesTitle: "Four core solutions. One clear scope.",
      servicesCta: "Send short project context",
      pricingEyebrow: "starting ranges",
      pricingTitle: "Starting ranges for entry scope.",
      pricingText: "We show entry ranges for the most common starting scopes. They give a reference point for a typical start, while the final scope is aligned around the project.",
      pricingRangeCue:
        "These are starting ranges for entry scope, not a list of one-off executions.",
      pricingItems: [
        {
          title: "Visual identity starter package",
          price: "from 700 € (BGN 1369.08)",
          value: "logo, logotype, and core rules for an ordered first rollout",
        },
        {
          title: "Social starter package",
          price: "from 25 € (BGN 48.90)",
          value: "core visuals and text direction for a working first presence",
        },
        {
          title: "Print starter package",
          price: "from 25 € (BGN 48.90)",
          value: "a first print piece prepared cleanly for real application",
        },
        {
          title: "Motion starter package",
          price: "from 50 € (BGN 97.79)",
          value: "a short motion or video asset for an ordered first rollout",
        },
      ],
      pricingNote:
        "BGN prices are calculated at the official fixed BNB exchange rate under Bulgaria’s euro adoption law.",
      pricingSecondaryNote:
        "The detailed price list is available on request. The starting scope is aligned around required formats, volume, and complexity.",
      pricingCta: "Send a project inquiry",
      processEyebrow: "process",
      processTitle: "Clear process. Ordered workflow.",
      processCta: "Start with short context",
      projectsEyebrow: "projects",
      projectsTitle: "Selected work with real application.",
      projectsText:
        "Identities, formats, and materials developed for specific brands and prepared for real use after the project.",
      projectsCta: "Explore selected work",
      aboutEyebrow: "about",
      aboutTitle: "We work with system, order, and real application.",
      aboutCta: "Send project context",
      contactEyebrow: "next step",
      contactTitle: "If the scope is clear, we continue from here.",
      contactText: "Send project context and we will return with scope, timing, and the next step for the task.",
      contactPrimaryCta: "Send project context",
      contactSecondaryCta: "Explore services",
    },
    services: {
      metaTitle: "Services",
      metaDescription:
        "Services by d . media for brand identity, content, graphic design, and advertising from a studio based in Sofia, Bulgaria.",
      eyebrow: "services",
      title: "Services for brand, content, and working presence.",
      text: "This is the working scope. Each service is structured to lead to a clear deliverable and immediate readiness for real use.",
      includes: "What it includes",
      audience: "Who it is for",
      result: "What result it delivers",
      ctaEyebrow: "next step",
      ctaTitle: "When the context is clear, the work starts in order.",
      ctaText: "Send project context, the need, and the deadline. We align scope, pricing, and the next step from there.",
      primaryCta: "Send project context",
      secondaryCta: "Explore projects",
    },
    projects: {
      metaTitle: "Projects",
      metaDescription:
        "Explore d . media projects in brand identity, design, content, and real files from completed work.",
      eyebrow: "projects",
      title: "Selected work with real application.",
      text: "This is the work that shows the clearest thinking, level of execution, and application after the project.",
      readingTitle: "What you will see",
      readingText: "Identities, visuals, and formats developed for real environments.",
      resultTitle: "What remains after the project",
      resultText: "Structured assets that can be used immediately and consistently.",
      selectedEyebrow: "curated selection",
      selectedTitle: "Selected projects",
      selectedText: "This is the curated work that shows the level, direction, and application most clearly.",
      archiveEyebrow: "archive",
      archiveTitle: "Project archive",
      archiveText:
        "The archive gathers the remaining work and shows the full range of output without placing it in the same role as the selected projects.",
      legacyEyebrow: "archived collections",
      ctaEyebrow: "next step",
      ctaTitle: "If you are looking for this level of clarity, start here.",
      ctaText: "Send a short project context, what needs to be developed, and what result you expect. We align the scope and the next step from there.",
      primaryCta: "Send short project context",
      secondaryCta: "Explore services",
    },
    projectDetail: {
      eyebrow: "project",
      context: "Context",
      solution: "Solution",
      usage: "How it is used",
      archive: "Archive",
      meta: "real files from the production work",
      back: "back to projects",
      applicationsEyebrow: "applications",
      applicationsTitle: "The available files from this project.",
      fallbackTitle: "Project",
    },
    about: {
      metaTitle: "About",
      metaDescription:
        "Learn more about d . media, the working approach, and access to the official brand book of the Sofia-based studio.",
      eyebrow: "about",
      text: "d . media is a studio built for clear work, consistency, and real use.",
      brandbookTitle: "Official brand book",
      brandbookText:
        "The brand book shows the core system, the usage rules, and the way the identity stays consistent in application.",
      primaryCta: "Send short context",
      secondaryCta: "Open the brand book",
    },
    contact: {
      metaTitle: "Contact",
      metaDescription:
        "Contact d . media about a new project in brand identity, content, design, or advertising.",
      eyebrow: "contact",
      title: "If you have a project, start with clear context.",
      text: "Send what needs to be developed, who it is for, the deadline, and the level of priority. We return with an assessment, scope, and next step.",
      needsTitle: "What to send",
      needsText:
        "Send the required service, a short context, a deadline, an approximate scale, and if available, references or existing materials.",
      responseTitle: "What we return",
      responseText:
        "We return with an assessment, scope, timeframe, pricing, or the need for a short clarification before the quote.",
      primaryCta: "Send project context",
      secondaryCta: "Explore services",
      mainContact: "Contact",
      channels: "Channels",
    },
    terms: {
      metaTitle: "Terms and Conditions",
      metaDescription:
        "Review d . media terms for commissioning, execution, documents, timelines, and project rights.",
      eyebrow: "terms",
      title: "Terms and Conditions",
      text: "Terms for using the services of d . media",
      shortLabel: "Short version",
      fullLabel: "Full version",
      shortTitle: "Short version",
      policyTitle: "Full version",
    },
    privacy: {
      metaTitle: "Privacy",
      metaDescription:
        "See how d . media processes personal data, on what legal basis, and what rights clients have.",
      eyebrow: "privacy",
      title: "Privacy and personal data protection",
      text: "d . media processes personal data in accordance with Regulation (EU) 2016/679 (GDPR) and the applicable Bulgarian legislation.",
      full: "Read the full policy",
      policyTitle: "Privacy policy",
    },
  },
} as const;

export function getPageCopy(locale: Locale) {
  return pageCopy[locale];
}
