import type { Locale } from "@/lib/i18n";

export const contactEmail = "contact@d-media.org";
export const contactPhone = "0892 494 495";
export const contactPhoneHref = "+359892494495";

const socialLinks = [
  { key: "instagram", handle: "/d.media_bg", href: "https://www.instagram.com/d.media_bg" },
  { key: "behance", handle: "/d-media", href: "https://www.behance.net/d-media" },
  { key: "linkedin", handle: "/d-media-bg", href: "https://www.linkedin.com/company/d-media-bg" },
  { key: "tiktok", handle: "/d.media_bg", href: "https://www.tiktok.com/@d.media_bg" },
  { key: "youtube", handle: "/d.media_BG", href: "https://www.youtube.com/@d.media_BG" },
] as const;

const localizedSiteContent = {
  bg: {
    mainNavigation: [
      { href: "/", label: "Начало" },
      { href: "/projects", label: "Проекти" },
      { href: "/blog", label: "Блог" },
      { href: "/services", label: "Услуги" },
      { href: "/pricing", label: "Цени" },
      { href: "/about", label: "За бранда" },
      { href: "/contact", label: "Контакти" },
    ],
    socials: {
      instagram: "Instagram",
      behance: "Behance",
      linkedin: "LinkedIn",
      tiktok: "TikTok",
      youtube: "YouTube",
    },
    coreServices: [
      {
        id: "brand-identity",
        title: "Бранд идентичност",
        text: "Лого, логотип и визуална система, подредени така, че брандът да стои ясен и разпознаваем.",
        includes: "Лого, логотип, цветова рамка, типография и основни правила за приложение.",
        audience: "За брандове, които имат нужда от ясен облик в началото или след период на размиване, не от козметична промяна без система.",
        result: "Получаваш logo система, цветова рамка и базови правила за сайт, документи и реклама.",
        detailHref: "/services/brand-identity",
        detailLabel: "Виж обхвата за бранд идентичност",
      },
      {
        id: "content",
        title: "Създаване на съдържание",
        text: "Текстове, визуални формати и серии съдържание, подредени в ясна комуникационна линия.",
        includes: "Текстове, визуални формати, серии съдържание, адаптации и работна структура за сайт, кампании и канали.",
        audience: "За брандове, които имат нужда от ясен изказ и последователно съдържание, не от отделни несвързани публикации.",
        result: "Получаваш съдържателен обхват с текстова и визуална логика, подготвен за реална употреба.",
        detailHref: "/services/content-creation",
        detailLabel: "Виж обхвата за създаване на съдържание",
      },
      {
        id: "social-media-management",
        title: "Управление на социални медии",
        text: "Социални канали, формати и календарна логика, подредени в стабилно присъствие.",
        includes: "Социални формати, корици, серии, адаптации, календарна рамка и работен ритъм за публикуване.",
        audience: "За брандове, които искат социалните им канали да изглеждат събрано и да работят в една посока.",
        result: "Получаваш подредена система за социално присъствие с ясни формати и следващ работен ред.",
        detailHref: "/services/social-media-management",
        detailLabel: "Виж обхвата за управление на социални медии",
      },
      {
        id: "web-design-development",
        title: "Уеб дизайн и разработка",
        text: "Сайтове и уеб платформи, изградени около яснота, скорост, видимост и реална употреба.",
        includes: "Корпоративни сайтове, портфолио сайтове, представителни сайтове, лендинг страници, дигитални платформи, многоезични сайтове, интеграции, SEO-ready и GEO-ready архитектура според проекта.",
        audience: "За брандове и бизнеси, които имат нужда от сайт като работеща платформа, не просто визуална страница.",
        result: "Получаваш бърз сайт с ясна структура, стабилна основа, възможност за поддръжка, интеграции и готовност за търсене и AI search.",
        detailHref: "/services/web-design-development",
        detailLabel: "Виж обхвата за уеб дизайн и разработка",
      },
      {
        id: "graphic-design",
        title: "Графичен дизайн",
        text: "Визуални материали за дигитална и печатна среда, изградени в ясен и разпознаваем стил.",
        includes: "Дигитални и печатни материали, корици, рекламни визии и формати за ежедневна употреба.",
        audience: "За брандове, които имат нужда от чисти решения за реална комуникация, не от случайни единични визии.",
        result: "Получаваш готови визии и файлове в точния формат за публикуване, печат или ежедневна употреба.",
        detailHref: "/services/graphic-design",
        detailLabel: "Виж обхвата за графичен дизайн",
      },
      {
        id: "advertising",
        title: "Реклама",
        text: "Рекламни визии и формати с фокус върху ясно послание, оферта и действие.",
        includes: "Рекламни визии, послания, кампанийни формати и адаптации за различни канали.",
        audience: "За бизнеси, които искат по-ясна оферта и по-добър отклик, не шумна комуникация без посока.",
        result: "Получаваш кампанийна визия, адаптация и готовност за реално пускане.",
        detailHref: "/services/advertising",
        detailLabel: "Виж обхвата за реклама",
      },
      {
        id: "additional-charges-rights",
        title: "Допълнителни начисления и права",
        text: "Приоритет, white-label, работа на място и права за използване, подредени като отделен обхват, когато проектът го изисква.",
        includes: "Приоритетни начисления, white-label, работа с клиент на място и рамки за лицензиране или прехвърляне на права.",
        audience: "За проекти, при които срокът, начинът на работа или правата за използване изискват отделна и ясна рамка.",
        result: "Получаваш ясна допълнителна ценова и правна рамка около основната услуга, без неясноти в края на проекта.",
        detailHref: "/services/additional-charges-rights",
        detailLabel: "Виж допълнителните начисления и права",
      },
    ],
    coreProcess: [
      { id: "01", title: "Запитване", text: "Изпращаш кратък контекст и какво трябва да се изработи." },
      { id: "02", title: "Обхват и оферта", text: "Подреждаме задачата, срока и ценовата рамка според проекта." },
      { id: "03", title: "Потвърждение", text: "След одобрение проектът влиза в работа по ясен план." },
      { id: "04", title: "Разработка", text: "Изграждаме материалите последователно и в съгласуван ред." },
      { id: "05", title: "Предаване", text: "Получаваш готовите файлове в уговорения формат, подготвени за реална употреба." },
    ],
    aboutNotes: [
      "В d . media работим между бранд идентичност, съдържание, уеб платформи, графичен дизайн и реклама. Целта е една: брандът да стои ясен, подреден и използваем във всяка точка на контакт.",
      "Подходът е системен. Проектът не се разглежда като единична визия, а като среда, в която знак, тон, сайт, формат и приложение трябва да работят заедно.",
      "Визуалната и комуникационната система има стойност само когато издържа извън презентацията. Тя трябва да работи в сайт, социални канали, документи, реклама и реални носители без да губи посока.",
      "Това изисква точен обхват, дисциплина в решенията и вкус в изпълнението. По-малко шум. Повече ред, последователност и приложение.",
      "След проекта не остават просто файлове. Остава система, която може да се използва, поддържа и развива с увереност.",
      "Точно тук е разликата: по-малко ефект, повече точност; по-малко показност, повече стойност.",
    ],
    aboutSummary: [
      "В d . media създаваме идентичност, съдържание, уеб платформи, дизайн и реклама като една работеща система.",
      "Всеки проект започва с ясен обхват и завършва с материал за реална употреба.",
      "Подходът е подреден, спокоен и точен, без шум и без излишни решения.",
      "Фокусът е върху последователност, приложение и стойност, която остава след проекта.",
      "Резултатът е бранд, който изглежда събран, разпознаваем и готов за работа.",
    ],
    testimonials: {
      eyebrow: "отзиви",
      title: "Какво казват клиентите за d . media.",
      text: "Подбрани отзиви от реални клиенти, представени на ниво бранд.",
      items: [
        {
          quote: "Професионално отношение и отлична изработка. Препоръчвам d . media.",
          name: "Teodora Peneva",
          source: "препоръка във Facebook",
        },
        {
          quote: "Brilliant work. Highly recommend.",
          name: "Hristo Kisyov",
          source: "препоръка във Facebook",
        },
        {
          quote: "С d . media се работи точно, бързо и с много добър усет към детайла.",
          name: "Yana Dimova",
          source: "препоръка във Facebook (откъс)",
        },
        {
          quote: "Доволни сме от комуникацията, професионалното отношение и крайния резултат.",
          name: "Tsvetina Asenov",
          source: "препоръка във Facebook (откъс)",
        },
      ],
    },
    termsSummary: [
      "Работата започва след потвърдена оферта или сключен договор.",
      "Специалните условия по конкретен проект имат предимство пред общата рамка.",
      "Срокове, цена, формати и обхват се определят предварително.",
      "Клиентът предоставя нужните материали и носи отговорност за правата върху тях.",
      "Готовите файлове се предават в уговорения формат и следват рамката на конкретната услуга.",
    ],
    termsSections: [
      { title: "Обхват", text: "Страницата Условия обобщава общите правила, по които d . media приема, изпълнява и предава услуги към клиенти." },
      { title: "Възлагане", text: "Запитването, офертата и потвърждението могат да формират работеща договорна рамка дори когато няма отделен хартиен договор." },
      { title: "Изпълнение", text: "Всеки проект се движи по предварително съгласувани срокове, спецификации, формати и точки на контакт." },
      { title: "Права и отговорности", text: "d . media изпълнява услугата с дължимото качество, а клиентът осигурява съдържание, обратна връзка и плащане в уговорения срок." },
      { title: "Интелектуална собственост", text: "Правата върху създадените материали се уреждат според конкретния проект и допълнителните уговорки за употреба." },
    ],
    privacySummary: [
      "Обработват се само данни, нужни за контакт, договорни отношения и плащания.",
      "Правните основания включват договор, преддоговорни отношения, законово задължение, легитимен интерес и съгласие.",
      "Съхранението следва определени срокове според вида на документацията.",
      "В повечето случаи данните не се споделят с трети страни извън законово изискуемите случаи.",
      "Всеки клиент има право на достъп, корекция, изтриване, ограничаване, възражение и преносимост.",
    ],
    privacySections: [
      { title: "Какви данни", text: "Имена, адрес, телефон, e-mail, платежна информация и технически идентификатори, когато това е нужно за услугата или сайта." },
      { title: "Защо", text: "За контакт, подготовка на оферти и договори, изпълнение на услуги, счетоводни нужди, защита при спорове и подобряване на съдържанието." },
      { title: "Колко дълго", text: "Сроковете следват вида на данните: кратко за кореспонденция, по-дълго за договори, фактури и счетоводни документи." },
      { title: "Как се пазят", text: "Данните се съхраняват при технически и организационни мерки за сигурност и се изтриват или анонимизират след изтичане на нужния срок." },
      { title: "Права", text: "Всеки клиент може да поиска информация, корекция, ограничаване, изтриване или възражение чрез директен контакт с d . media." },
    ],
  },
  en: {
    mainNavigation: [
      { href: "/", label: "Home" },
      { href: "/projects", label: "Projects" },
      { href: "/blog", label: "Blog" },
      { href: "/services", label: "Services" },
      { href: "/pricing", label: "Pricing" },
      { href: "/about", label: "About" },
      { href: "/contact", label: "Contacts" },
    ],
    socials: {
      instagram: "Instagram",
      behance: "Behance",
      linkedin: "LinkedIn",
      tiktok: "TikTok",
      youtube: "YouTube",
    },
    coreServices: [
      {
        id: "brand-identity",
        title: "Brand Identity",
        text: "Logo, logotype, and a visual system structured to keep the brand clear and recognisable.",
        includes: "Logo, logotype, colour framework, typography, and core application rules.",
        audience: "For brands that need a clear visual direction from the start or after a period of drift, not a cosmetic change without a system.",
        result: "You get a logo system, colour framework, and core rules for website, documents, and advertising.",
        detailHref: "/services/brand-identity",
        detailLabel: "View the brand identity scope",
      },
      {
        id: "content",
        title: "Content Creation",
        text: "Copy, visual formats, and content series arranged into a clear communication line.",
        includes: "Copy, visual formats, content series, adaptations, and working structure for websites, campaigns, and channels.",
        audience: "For brands that need a clear voice and consistent content, not disconnected standalone posts.",
        result: "You get a content scope with copy and visual logic prepared for real use.",
        detailHref: "/services/content-creation",
        detailLabel: "View the content creation scope",
      },
      {
        id: "social-media-management",
        title: "Social Media Management",
        text: "Social channels, formats, and calendar logic organised into a stable presence.",
        includes: "Social formats, covers, series, adaptations, calendar framework, and a working publishing rhythm.",
        audience: "For brands that need their social channels to feel coherent and move in one direction.",
        result: "You get an organised social presence system with clear formats and a next working rhythm.",
        detailHref: "/services/social-media-management",
        detailLabel: "View the social media management scope",
      },
      {
        id: "web-design-development",
        title: "Web Design & Development",
        text: "Websites and digital platforms built around clarity, speed, visibility, and real use.",
        includes: "Corporate websites, portfolio websites, presentation websites, landing pages, digital platforms, multilingual websites, integrations, SEO-ready and GEO-ready architecture shaped around the project.",
        audience: "For brands and businesses that need a website as a working platform, not just a visual page.",
        result: "You get a fast website with clear structure, stable delivery, maintenance potential, integrations, and readiness for search and AI search.",
        detailHref: "/services/web-design-development",
        detailLabel: "View the web design and development scope",
      },
      {
        id: "graphic-design",
        title: "Graphic Design",
        text: "Visual materials for digital and print environments, built in a clear and recognisable style.",
        includes: "Digital and print materials, covers, campaign visuals, and day-to-day communication formats.",
        audience: "For brands that need clean solutions for real communication, not random one-off visuals.",
        result: "You get ready visuals and files in the right format for publishing, print, or day-to-day use.",
        detailHref: "/services/graphic-design",
        detailLabel: "View the graphic design scope",
      },
      {
        id: "advertising",
        title: "Advertising",
        text: "Advertising visuals and formats focused on clear messaging, offer clarity, and action.",
        includes: "Campaign visuals, messaging, advertising formats, and channel-specific adaptations.",
        audience: "For businesses that need a clearer offer and stronger response, not noisy communication without direction.",
        result: "You get a campaign visual, adaptation, and launch readiness.",
        detailHref: "/services/advertising",
        detailLabel: "View the advertising scope",
      },
      {
        id: "additional-charges-rights",
        title: "Additional Charges and Rights",
        text: "Priority, white-label work, on-site work, and usage rights organised as a separate scope when the project requires it.",
        includes: "Priority add-ons, white-label work, on-site client work, and licensing or rights-transfer frameworks.",
        audience: "For projects where timing, working mode, or usage rights need a separate and explicit framework.",
        result: "You get a clear additional pricing and rights layer around the core service, without ambiguity at the end of the project.",
        detailHref: "/services/additional-charges-rights",
        detailLabel: "View additional charges and rights",
      },
    ],
    coreProcess: [
      { id: "01", title: "Inquiry", text: "You send short context and what needs to be created." },
      { id: "02", title: "Scope and quote", text: "We define the task, timeline, and pricing framework around the project." },
      { id: "03", title: "Confirmation", text: "Once approved, the project moves into work through a clear plan." },
      { id: "04", title: "Development", text: "We build the materials in a consistent and coordinated order." },
      { id: "05", title: "Delivery", text: "You receive the final files in the agreed format, ready for real use." },
    ],
    aboutNotes: [
      "At d . media, we work between brand identity, content, web platforms, graphic design, and advertising. The goal is simple: the brand should feel clear, ordered, and usable at every point of contact.",
      "The approach is systematic. A project is not treated as a single visual, but as an environment in which sign, tone, website, format, and application need to work together.",
      "A visual and communication system has value only when it holds up beyond a presentation. It needs to work across a website, social channels, documents, advertising, and real-world formats without losing direction.",
      "That requires a precise scope, discipline in decision-making, and taste in execution. Less noise. More order, consistency, and application.",
      "What remains after the project is not just a folder of files. It is a system we build to be used, maintained, and developed with confidence.",
      "That is the difference: less effect, more precision; less display, more value.",
    ],
    aboutSummary: [
      "At d . media, we create identity, content, web platforms, design, and advertising as one working system.",
      "Every project begins with a clear scope and ends with material ready for real use.",
      "The approach is ordered, calm, and precise, without noise and without unnecessary decisions.",
      "The focus is on consistency, application, and value that remains after the project.",
      "The result is a brand that feels cohesive, recognisable, and ready to work.",
    ],
    testimonials: {
      eyebrow: "client feedback",
      title: "What clients say about d . media.",
      text: "Selected feedback from real clients, presented at brand level.",
      items: [
        {
          quote: "Professional attitude and excellent execution. We recommend d . media.",
          name: "Teodora Peneva",
          source: "Facebook recommendation",
        },
        {
          quote: "Brilliant work. Highly recommend.",
          name: "Hristo Kisyov",
          source: "Facebook recommendation",
        },
        {
          quote: "Working with d . media feels precise, fast, and carefully handled down to the details.",
          name: "Yana Dimova",
          source: "Facebook recommendation · excerpt",
        },
        {
          quote: "We were very satisfied with the communication, the professional attitude, and the final result.",
          name: "Tsvetina Asenov",
          source: "Facebook recommendation · excerpt",
        },
      ],
    },
    termsSummary: [
      "Work begins after a confirmed offer or a signed agreement.",
      "Specific project terms take precedence over the general framework.",
      "Timelines, price, formats, and scope are defined in advance.",
      "The client provides the required materials and remains responsible for the rights attached to them.",
      "Final files are delivered in the agreed format and follow the framework of the specific service.",
    ],
    termsSections: [
      { title: "Scope", text: "The Terms page summarises the general rules under which d . media accepts, delivers, and hands over services to clients." },
      { title: "Commissioning", text: "The inquiry, offer, and confirmation can form a valid working agreement even without a separate paper contract." },
      { title: "Execution", text: "Each project moves through previously agreed timelines, specifications, formats, and contact points." },
      { title: "Rights and responsibilities", text: "d . media delivers the service with due quality, while the client provides content, feedback, and payment within the agreed timeframe." },
      { title: "Intellectual property", text: "Rights over created materials are arranged according to the specific project and any additional agreements on usage." },
    ],
    privacySummary: [
      "Only data required for contact, contractual relations, and payment is processed.",
      "Legal grounds include contract, pre-contractual relations, legal obligation, legitimate interest, and consent.",
      "Storage follows defined periods depending on the type of documentation.",
      "In most cases, data is not shared with third parties outside legally required situations.",
      "Every client has the right to access, correct, erase, restrict, object, and request portability.",
    ],
    privacySections: [
      { title: "What data", text: "Names, address, phone number, e-mail, payment information, and technical identifiers when they are needed for the service or the site." },
      { title: "Why", text: "For contact, preparing offers and agreements, delivering services, accounting needs, protection in disputes, and improving content." },
      { title: "How long", text: "Retention periods depend on the type of data: shorter for correspondence, longer for agreements, invoices, and accounting documents." },
      { title: "How it is protected", text: "Data is stored with technical and organisational security measures and is deleted or anonymised after the necessary period expires." },
      { title: "Rights", text: "Every client can request information, correction, restriction, erasure, or objection through direct contact with d . media." },
    ],
  },
} as const;

export function getSiteContent(locale: Locale) {
  const content = localizedSiteContent[locale];

  return {
    ...content,
    socials: socialLinks.map((social) => ({
      label: content.socials[social.key],
      handle: social.handle,
      href: social.href,
    })),
  };
}
